import {COURSE,lesson,section,q} from './course.mjs';
COURSE.push({
 id:'anemia',title:'Anemia',label:'Blood & oxygen transport',week:'Week 2',icon:'droplet',color:'#b7476d',source:'sources/anemia-slides.pdf',
 description:'Connect red-cell production, cell size, hemoglobin, and the different causes of anemia.',
 lessons:[
 lesson('a1','Red cells, oxygen & the CBC','2–8','Anemia reduces the blood’s oxygen-carrying capacity. Ask whether cells are lost, destroyed, or underproduced.',[
 section('What red blood cells do','Red blood cells (RBCs), also called erythrocytes, carry hemoglobin (Hb or Hgb), the protein that transports oxygen. When hemoglobin is low, less oxygen can be carried to tissues. This helps explain fatigue, weakness, pallor, breathlessness, and dizziness. Tachycardia can be a compensatory attempt to deliver more blood per minute.'),
 section('How the body makes more','When oxygen delivery is inadequate, the kidneys can increase erythropoietin (EPO), a hormone that signals bone marrow to produce RBCs. Reticulocytes are young red cells recently released from marrow. Production still requires functioning marrow and building materials such as iron and vitamin B12. Chronic kidney disease can impair the EPO signal; inflammation can also interfere with production and iron availability.'),
 section('Decode the complete blood count','A complete blood count (CBC) includes hemoglobin, hematocrit (Hct, the fraction of blood volume occupied by RBCs), and blood-cell counts. Mean corpuscular volume (MCV) describes average RBC size: microcytic = small, normocytic = usual size, macrocytic = large. Mean corpuscular hemoglobin concentration (MCHC) describes hemoglobin concentration within cells. Hypochromic means relatively pale/low concentration. A smear shows cell appearance. Size and color help narrow the cause, but do not diagnose it alone.')
 ],['Low hemoglobin','Less oxygen carried','Tissue oxygen shortage','Symptoms & compensation'],'MCV = volume/size. MCHC = hemoglobin concentration.',[
 ['MCV','Mean corpuscular volume: average red-cell size.','Low suggests microcytosis; high suggests macrocytosis.'],
 ['MCHC','Mean corpuscular hemoglobin concentration: hemoglobin concentration within RBCs.','A low value can accompany pale, hypochromic cells.'],
 ['EPO','Erythropoietin: a hormone, mainly from the kidneys, that stimulates RBC production.','Marrow and nutrients must be available for an adequate response.']
 ],[
 q('What is the main functional consequence of anemia?','Reduced oxygen-carrying capacity','Less hemoglobin means less capacity to carry oxygen. Symptoms reflect tissue oxygen shortage and the body’s attempt to compensate.',[['Always excessive oxygen delivery','This is the opposite of the core problem.'],['Guaranteed absence of all white cells','Some anemias affect only RBCs.'],['Always a mechanical pulmonary obstruction','That describes an obstructive cause of shock, not anemia in general.']]),
 q('Which index tells you average RBC size?','MCV','Mean corpuscular volume measures average cell volume. It separates microcytic, normocytic, and macrocytic patterns.',[['MCHC','MCHC refers to hemoglobin concentration in cells.'],['TSH','TSH stimulates the thyroid gland.'],['CD4 count','CD4 count evaluates a type of immune cell.']]),
 q('What does erythropoietin mainly stimulate?','Red-cell production in bone marrow','EPO is a signal that encourages erythropoiesis. It does not directly replace the iron or B12 needed to make cells.',[['HIV integration','That is a viral lifecycle process.'],['Thyroid hormone destruction','EPO is not the main regulator of thyroid hormone.'],['Immediate external blood loss','EPO supports production, not bleeding.']]),
 q('A patient has low Hb and small RBCs. Which description fits the cells?','Microcytic','Micro means small; cytic refers to cells. Low Hb establishes the oxygen-carrier problem, while low MCV describes a size pattern that helps narrow the cause.',[['Macrocytic','Macrocytic means large, not small.'],['Atonic','Atonic describes loss of muscle tone.'],['Exophthalmic','Exophthalmos refers to protruding eyes.']],'Apply'),
 q('Why may anemia cause tachycardia?','The heart tries to increase oxygen delivery by pumping more blood','When each volume of blood carries less oxygen, increasing flow may partly compensate. This does not fix the underlying deficiency.',[['Hemoglobin always stimulates a slower pulse','Reduced oxygen delivery can lead to an increased pulse.'],['Tachycardia proves every anemia is iron deficiency','Several anemia types can cause compensatory tachycardia.'],['RBC size directly counts heartbeats','Cell size is an index, not a pulse measurement.']],'Apply'),
 q('Why can chronic kidney disease contribute to anemia?','Reduced erythropoietin production can limit marrow stimulation','The kidney’s EPO signal helps maintain RBC production. A weaker signal can reduce production even when the anemia is not due to bleeding.',[['The kidneys normally make all hemoglobin inside urine','Hemoglobin is formed in developing red cells.'],['Every kidney disorder creates excess intrinsic factor','Intrinsic factor comes from the stomach, not the kidneys.'],['Kidney disease always makes RBCs larger than normal','A size pattern alone is not universal for kidney disease.']],'Apply')
 ]),
 lesson('a2','Iron deficiency: small, pale cells','7, 9–11','Iron is a building material for hemoglobin. Find out why the stores became depleted.',[
 section('From missing iron to the cell pattern','Iron is needed to build hemoglobin. With inadequate iron, developing RBCs cannot accumulate their usual hemoglobin supply and are often smaller and paler: microcytic and hypochromic. Anisocytosis means varied cell sizes; poikilocytosis means varied cell shapes. Both may appear on a blood smear but are not exclusive to iron deficiency.'),
 section('Look for the reason, not only the label','Causes include chronic blood loss, insufficient intake, poor absorption, or greater demand during growth or pregnancy. Heavy menstrual bleeding and gastrointestinal bleeding are examples. Pica means craving nonfood substances, sometimes ice. Brittle or spoon-shaped nails and glossitis (an inflamed tongue) can be additional clues, alongside ordinary anemia symptoms.'),
 section('Read the iron studies','Ferritin is a marker of iron stores; a low value strongly supports depleted stores. Ferritin can rise with inflammation, so a normal or high value does not always exclude iron deficiency in an inflammatory setting. Serum iron is often low and total iron-binding capacity (TIBC) often rises in uncomplicated iron deficiency. Treatment replenishes iron and addresses the underlying cause, especially ongoing blood loss.')
 ],['Iron stores depleted','Less hemoglobin made','Small, pale RBCs','Reduced oxygen transport'],'Iron deficiency: low stores, low Hb, often low MCV and MCHC.',[
 ['Ferritin','A protein associated with stored iron; its blood level helps estimate iron stores.','Low ferritin supports depleted stores, but inflammation can raise it.'],
 ['TIBC','Total iron-binding capacity: a measure of the blood’s capacity to bind iron.','It often rises in uncomplicated iron deficiency.'],
 ['Pica','Craving or eating nonfood substances, including a characteristic craving for ice in some patients.','It is a clue that may accompany iron deficiency, not a stand-alone diagnosis.']
 ],[
 q('What RBC pattern is typical of established iron-deficiency anemia?','Microcytic and hypochromic','Too little iron limits hemoglobin synthesis. Developing cells are often small and relatively pale.',[['Always very large cells with normal iron stores','That is not the typical iron-deficiency pattern.'],['No effect on hemoglobin synthesis','Iron is essential to hemoglobin synthesis.'],['Only low CD4 cells','CD4 cells are immune cells, not the defining RBC pattern.']]),
 q('Which finding strongly supports depleted iron stores?','Low ferritin','Ferritin is associated with stored iron. A low result supports iron depletion, while inflammation can complicate interpretation of higher results.',[['High free T4','This is a thyroid hormone result.'],['A positive HIV antibody test','This assesses HIV infection, not iron stores.'],['A generalized EEG discharge','This concerns brain electrical activity.']]),
 q('Which is a common reason for iron deficiency?','Chronic blood loss','Repeated losses can remove more iron than the body replaces. Identifying the bleeding source is part of treatment.',[['Excessive dietary iron in every case','Excess iron is not the defining shortage.'],['Too much intrinsic factor','Intrinsic factor relates to B12 absorption.'],['Always a single mutated beta-globin gene','Inherited globin changes are different mechanisms.']]),
 q('A patient with heavy menstrual bleeding has fatigue, low ferritin, and low MCV. What best connects these findings?','Repeated blood loss has depleted iron needed for hemoglobin','The history and iron-store result support iron deficiency. Small cells fit the resulting hemoglobin-production problem.',[['Menstrual bleeding increases iron stores','Blood loss removes iron from the body.'],['Low MCV proves B12 deficiency','B12 deficiency typically causes macrocytosis.'],['Ferritin is only a marker of thyroid activity','Ferritin relates to iron stores.']],'Apply'),
 q('Why should the cause of blood loss be addressed alongside iron replacement?','Ongoing loss can keep depleting the replaced iron','Replacing a nutrient without stopping repeated loss may fail to correct the problem sustainably. Treatment follows the cause as well as the deficiency.',[['Iron tablets permanently stop every source of bleeding','Iron replenishes stores; it does not directly stop all bleeding.'],['The source of bleeding never matters','It determines the ongoing loss and may require specific treatment.'],['Blood loss has no iron content','Hemoglobin in lost RBCs contains iron.']],'Apply'),
 q('Which statement about ferritin is most accurate?','Inflammation can raise ferritin and complicate interpretation','A low level supports depleted stores. A normal or raised result must be interpreted with clinical context and other iron studies.',[['A high ferritin always excludes iron deficiency','Inflammation can mask depleted stores.'],['Ferritin measures the number of seizures','It does not assess seizure frequency.'],['Ferritin and MCV are the same measurement','One concerns iron storage; the other concerns RBC size.']],'Apply')
 ]),
 lesson('a3','Vitamin B12 & pernicious anemia','12–14','B12 supports DNA synthesis and nervous-system function. Pernicious anemia is one cause of deficiency.',[
 section('Why cells become large','Vitamin B12 is needed for normal DNA synthesis. When it is deficient, developing RBCs cannot divide and mature normally, producing a megaloblastic, often macrocytic pattern. Low hemoglobin still reduces oxygen transport. Unlike iron deficiency, the typical size clue is a high MCV rather than a low one.'),
 section('Why there may be tingling','B12 is also important for nervous-system function. Deficiency may cause numbness, tingling, balance problems, or cognitive changes, sometimes even without severe anemia. These clues matter because correcting hemoglobin alone does not establish that a B12-related nerve problem has been addressed.'),
 section('Deficiency and pernicious anemia are not identical','Dietary deficiency, gastrointestinal disease or surgery, and malabsorption can all cause low B12. Pernicious anemia is an autoimmune condition that damages the stomach’s ability to provide intrinsic factor, a protein needed for normal absorption of dietary B12 in the terminal ileum. B12 injections bypass the absorption problem. Clinicians may also use high-dose oral B12 in selected circumstances; the slide note that oral treatment never works is too absolute. Serum B12 and other tests help clarify the cause; the Schilling test in the slides is historical.')
 ],['B12 deficiency','Impaired DNA synthesis','Abnormal cell maturation','Macrocytic anemia ± nerve symptoms'],'B12: big cells and possible nerve clues. Pernicious: absorption problem.',[
 ['Intrinsic factor','A stomach-produced protein needed for normal dietary B12 absorption.','Autoimmune loss can cause pernicious anemia despite an adequate dietary intake.'],
 ['Megaloblastic','Abnormal maturation due to impaired DNA synthesis, often producing large RBCs.','Vitamin B12 and folate deficiencies can cause this pattern.'],
 ['Pernicious anemia','An autoimmune cause of B12 malabsorption linked to intrinsic-factor deficiency.','It is a subset of B12 deficiency, not a synonym for every B12 deficiency.']
 ],[
 q('Which size pattern is typical of B12-deficiency anemia?','Macrocytic','Impaired DNA synthesis interferes with normal division and maturation, often producing large red cells and an increased MCV.',[['Microcytic in every case','Microcytosis more strongly suggests other causes such as iron deficiency or thalassemia.'],['No possible cell changes','B12 deficiency can alter RBC maturation.'],['Only a low platelet volume','That does not describe the typical red-cell pattern.']]),
 q('Why does lack of intrinsic factor matter?','It impairs normal dietary vitamin B12 absorption','Intrinsic factor supports absorption in the terminal ileum. Its loss can cause deficiency even when dietary B12 intake is adequate.',[['It directly stops all heart contractions','That is not intrinsic factor’s function.'],['It causes HIV to attach to CD4','HIV attachment uses different proteins.'],['It prevents iron from existing in any food','It is specifically important for B12 absorption.']]),
 q('Which additional symptom especially raises concern for B12 deficiency?','Numbness and tingling in the hands or feet','B12 deficiency can affect nerves as well as blood-cell maturation. Neurologic changes deserve attention, even if anemia is mild.',[['Brief staring with immediate recovery alone','That is more characteristic of an absence-seizure description.'],['Urticaria immediately after a bee sting alone','That suggests an allergic reaction.'],['Exophthalmos alone','This can occur in Graves-related eye disease.']]),
 q('A patient eats B12-containing foods but has intrinsic-factor antibodies and macrocytic anemia. What fits?','Pernicious anemia causing malabsorption','Adequate intake does not guarantee absorption. Autoimmune intrinsic-factor impairment explains deficiency despite B12 in the diet.',[['Iron deficiency proved by a high MCV','Iron deficiency usually has a lower MCV.'],['B12 deficiency is impossible with adequate intake','Malabsorption can cause deficiency despite adequate intake.'],['All B12 deficiency is caused only by vegetarian diets','Several dietary and nondietary causes exist.']],'Apply'),
 q('Why are B12 injections commonly used for pernicious anemia?','They bypass the gastrointestinal absorption barrier','Injection provides B12 without relying on normal intrinsic-factor-dependent dietary absorption. Treatment selection depends on the clinical situation.',[['They restore every lost red cell instantly','New cell production and recovery take time.'],['They directly replace the thyroid gland','They do not replace thyroid tissue.'],['They remove a pulmonary embolus','They do not treat mechanical obstruction.']],'Apply'),
 q('Which statement best distinguishes pernicious anemia from B12 deficiency generally?','Pernicious anemia is one autoimmune cause of B12 deficiency','B12 can also be low because of dietary insufficiency, intestinal problems, or surgery. Identifying the cause guides the approach.',[['The terms always mean exactly the same cause','Pernicious anemia is more specific.'],['Pernicious anemia is simply low dietary iron','It concerns B12 malabsorption.'],['B12 deficiency never affects nerves','Neurologic effects are important possible manifestations.']],'Apply')
 ],{update:'Clinical update: injections are common for malabsorption or severe deficiency, but high-dose oral B12 can be effective in selected patients. The Schilling test is historical.',ref:{label:'NIH · Vitamin B12',url:'https://ods.od.nih.gov/factsheets/VitaminB12-HealthProfessional/'}}),
 lesson('a4','Aplastic anemia: marrow failure','15–17','The marrow may underproduce red cells, white cells, and platelets together.',[
 section('The factory is the problem','Bone marrow produces the major blood-cell lines. In aplastic anemia, blood-forming cells are severely reduced and marrow becomes hypocellular, often with fatty replacement. RBCs may be ordinary in size, but there are too few. White blood cells (WBCs) and platelets can also be low. Low counts in all three lines are called pancytopenia.'),
 section('Match each cell line to its consequence','Too few RBCs means fatigue, pallor, and reduced oxygen-carrying capacity. Too few infection-fighting WBCs, particularly neutrophils, increases infection risk. Too few platelets increases bleeding risk, bruising, and petechiae, the small pinpoint spots caused by bleeding under the skin. This is more than a single nutrient shortage.'),
 section('Diagnosis and management follow marrow function','A CBC shows the affected cell lines and a marrow biopsy evaluates marrow cellularity. Causes can include immune-mediated injury, drugs or chemicals, radiation, some infections, or inherited conditions; many cases lack an identified trigger. Management depends on severity and cause and may include supportive transfusions, treatment of infection, immunosuppressive therapy, or hematopoietic stem-cell transplantation. Do not memorize one survival percentage as applying to every patient.')
 ],['Marrow failure','Fewer RBCs, WBCs & platelets','Anemia + infection risk + bleeding risk'],'Three cell lines down: oxygen, defense, clotting.',[
 ['Pancytopenia','Low counts in red cells, white cells, and platelets.','It connects fatigue, infection risk, and bleeding in marrow failure.'],
 ['Petechiae','Small pinpoint skin spots caused by bleeding.','They can appear when platelet numbers are too low.'],
 ['Hypocellular marrow','Marrow with too few blood-forming cells.','It supports a production-failure explanation for low circulating counts.']
 ],[
 q('What is the basic mechanism of aplastic anemia?','Failure of bone marrow blood-cell production','The marrow cannot produce adequate blood-cell lines. This differs from destruction of normally produced RBCs.',[['Only accelerated destruction of HbS','That is a sickle-cell hemolysis mechanism.'],['Always excess circulating platelets','Platelets can be reduced.'],['Only thyroid hormone overproduction','That is a different endocrine problem.']]),
 q('Which group of findings best fits pancytopenia?','Low RBCs, low WBCs, and low platelets','Pancytopenia means multiple major cell lines are reduced. Each contributes to a different risk.',[['High T3, high T4, and low TSH','That is a thyroid pattern.'],['Only low serum iron','That does not establish all three cell lines are low.'],['Normal RBCs with only a high pulse','A pulse alone is not a blood-cell count.']]),
 q('Why does a low platelet count increase concern?','It increases bleeding risk','Platelets support clot formation. Reduced numbers can cause bruising, petechiae, and bleeding.',[['It eliminates the need for oxygen','Platelets do not replace oxygen transport.'],['It directly raises thyroid hormone','Platelets do not regulate the thyroid axis.'],['It proves all RBCs are too large','Platelet count does not establish RBC size.']]),
 q('Fatigue, repeated infections, and petechiae occur with low counts in all three cell lines. Which mechanism best links them?','Reduced marrow production','RBC reduction explains oxygen-related symptoms; WBC reduction explains infection risk; platelet reduction explains bleeding. A common marrow problem links the findings.',[['Only a dietary iron shortage explains every cell line','Iron deficiency alone does not typically cause this pancytopenic pattern.'],['Only a transient absence seizure','That does not explain persistent low blood-cell counts.'],['Primary thyroid stimulation by antibodies','That is the Graves mechanism.']],'Apply'),
 q('Why is bone marrow biopsy useful in suspected aplastic anemia?','It assesses the marrow’s blood-forming cellularity','Low peripheral counts show the outcome. Examining marrow helps assess whether the production factory itself is depleted.',[['It measures the exact number of HIV antibodies','That requires blood-based testing, not marrow cellularity assessment.'],['It is only a thyroid hormone test','Marrow biopsy evaluates marrow tissue.'],['It directly replaces the missing platelets','Biopsy is diagnostic, not a platelet transfusion.']],'Apply'),
 q('Which treatment can restore a source of healthy blood-forming cells in selected severe cases?','Hematopoietic stem-cell transplantation','Transplanted blood-forming stem cells can establish marrow production. Suitability and risks are assessed by a specialist team.',[['An antihistamine alone','This does not restore marrow production.'],['Only a beta-blocker','This affects heart-rate-related symptoms, not marrow replacement.'],['Routine iodide for every case','Iodide is not a universal marrow-failure treatment.']],'Apply')
 ]),
 lesson('a5','Hemolytic anemia: cells destroyed early','18–20','Hemolysis means RBC breakdown. The marrow may try to replace cells that are being lost too quickly.',[
 section('Destruction, not simply underproduction','RBCs have a finite lifespan. Hemolytic anemia occurs when their destruction is accelerated enough that replacement cannot maintain normal circulating hemoglobin. Causes include immune injury, inherited cell abnormalities, some infections, mechanical damage, and other conditions. Destruction can occur within vessels or mainly in organs such as the spleen.'),
 section('Why jaundice and dark urine can appear','Breaking down heme generates bilirubin. Increased breakdown can raise unconjugated bilirubin and cause jaundice, the yellowing of skin or eyes. With intravascular hemolysis, free hemoglobin may appear in plasma or urine, producing hemoglobinemia or hemoglobinuria. Not every form has all these signs. Clotting complications depend on the specific disorder rather than occurring in every hemolytic anemia.'),
 section('Use the replacement response and the cause tests','Reticulocytes often rise when the marrow has the resources to respond. Lactate dehydrogenase (LDH) may rise with cell breakdown, and haptoglobin may fall as it binds free hemoglobin. The direct antiglobulin test (DAT, direct Coombs test) detects antibodies or complement attached to RBCs and can support an immune cause. A negative test does not exclude every kind of hemolysis. Treatment targets the cause.')
 ],['Early RBC destruction','Less circulating hemoglobin','More breakdown products','Anemia ± jaundice'],'Hemolysis: cells break; bilirubin rises; marrow may respond.',[
 ['Hemolysis','Premature breakdown of red blood cells.','It can cause anemia when destruction outpaces replacement.'],
 ['Reticulocyte','A young red blood cell recently released from marrow.','A rise often indicates a marrow attempt to replace lost or destroyed cells.'],
 ['DAT / Coombs','Direct antiglobulin test: detects antibodies or complement attached to RBCs.','It evaluates an immune-mediated mechanism, not every possible cause of hemolysis.']
 ],[
 q('What does hemolysis mean?','Breakdown of red blood cells','When RBCs are destroyed faster than adequate replacement, circulating hemoglobin falls and anemia develops.',[['Reduced thyroid size','That is unrelated to the word hemolysis.'],['Increased production of every platelet','Hemolysis concerns RBC destruction.'],['A brief loss of muscle tone','That describes atonic activity.']]),
 q('Why may jaundice accompany hemolytic anemia?','Increased heme breakdown produces more bilirubin','Bilirubin is a heme-breakdown product. Increased RBC destruction can raise its level and cause yellowing.',[['Jaundice is always proof of dietary B12 deficiency','Several conditions can cause jaundice, including hemolysis.'],['Hemoglobin turns directly into TSH','TSH is not a hemoglobin-breakdown product.'],['The spleen produces excessive iodine','That does not explain bilirubin-related jaundice.']]),
 q('What does a direct Coombs test evaluate?','Antibodies or complement attached to RBCs','The test can support immune-mediated RBC destruction. It is not a general measure of iron stores or cell size.',[['Average RBC size','Mean corpuscular volume measures average red-cell size; the DAT assesses immune binding on cells.'],['Stored iron alone','Ferritin relates to iron stores.'],['The viral RNA amount in blood','That is evaluated by viral-load testing.']]),
 q('A patient has anemia, jaundice, elevated LDH, and an increased reticulocyte count. What is a reasonable mechanism?','Accelerated RBC destruction with a marrow response','The breakdown markers and young-cell response support hemolysis when considered with the rest of the assessment.',[['Complete failure of marrow response is proved','Increased reticulocytes suggest marrow is responding.'],['Only isolated thyroid overproduction explains all results','The described pattern points to red-cell breakdown.'],['The patient must have normal hemoglobin','The scenario specifically states anemia.']],'Apply'),
 q('Why may reticulocytes rise in hemolysis?','The marrow attempts to replace destroyed RBCs','When the marrow is capable and has the required nutrients, it responds to shortened RBC survival by increasing production.',[['Reticulocytes are older damaged RBCs','Reticulocytes are young RBCs, so an increase usually reflects new production rather than only old-cell accumulation.'],['High reticulocytes always mean aplastic marrow failure','Aplastic marrow commonly has an inadequate production response.'],['Hemolysis makes bone marrow irrelevant','Replacement production remains important.']],'Apply'),
 q('Which interpretation of a negative direct Coombs test is appropriate?','It does not rule out every nonimmune hemolytic cause','The test focuses on antibodies or complement on RBCs. Other mechanisms can destroy RBCs without a positive result.',[['All hemolysis is impossible','Nonimmune hemolysis can occur.'],['Iron stores must be normal','The DAT is not an iron-store measurement.'],['The result automatically proves sickle cell disease','Specific hemoglobin testing is needed.']],'Apply')
 ]),
 lesson('a6','Sickle cell: hemolysis & vessel blockage','21–26','Abnormal hemoglobin can make RBCs rigid, causing both early destruction and impaired blood flow.',[
 section('The hemoglobin changes first','Hemoglobin S (HbS) contains an altered beta-globin chain. When deoxygenated, HbS can polymerize, joining into long structures. Cells become less flexible and may take on a sickled shape. Repeated sickling can damage the membrane. Two important outcomes follow: premature destruction produces anemia, and vaso-occlusion interrupts blood flow to tissues.'),
 section('Understand inheritance and complications','In the simplified HbSS model, two HbS alleles cause sickle cell anemia, while one HbS and one usual HbA allele produces trait. Sickle cell disease also includes other inherited combinations such as HbSC and HbS/beta-thalassemia. A trait carrier usually lacks the disease pattern, although rare complications can occur. Vaso-occlusion causes ischemic pain and organ damage. Acute chest syndrome and stroke are serious complications; acute chest syndrome has several possible mechanisms, not only infarction.'),
 section('Management addresses more than pain','Infection, dehydration, and hypoxemia can contribute to sickling events. Care includes appropriate pain treatment, avoiding triggers, carefully assessed hydration, vaccination and infection prevention, and transfusion when indicated. Hydroxyurea can raise fetal hemoglobin (HbF) and reduce sickling complications. Hemoglobin testing helps identify the disorder. The slides’ absolute statement of no cure is outdated: transplantation can be curative for some patients, and gene therapies are available for selected patients.')
 ],['Deoxygenated HbS polymerizes','RBCs become rigid','Hemolysis + vaso-occlusion','Anemia + ischemic pain'],'Sickle cell has two problems: broken cells and blocked flow.',[
 ['HbS','Hemoglobin S: an abnormal hemoglobin associated with sickling.','Its deoxygenated form can polymerize and make cells rigid.'],
 ['Vaso-occlusion','Blockage of small-vessel blood flow by the disease process.','Ischemia explains pain and can injure organs.'],
 ['HbF','Fetal hemoglobin: a hemoglobin type that inhibits HbS sickling when increased.','Raising HbF is an important effect of hydroxyurea.']
 ],[
 q('What happens to deoxygenated HbS?','It can polymerize into structures that stiffen RBCs','HbS molecules can join into long structures, reducing flexibility and promoting sickling.',[['It becomes intrinsic factor','Hemoglobin does not become the B12-absorption protein.'],['It always produces perfectly flexible normal RBCs','Polymerization has the opposite effect.'],['It directly raises TSH','This is not the thyroid feedback mechanism.']]),
 q('What are the two major consequences of sickling?','Hemolysis and vaso-occlusion','Early cell destruction causes anemia, while obstructed small-vessel flow causes tissue ischemia and pain.',[['Only high platelet production and high TSH','These are not the two central consequences.'],['Only low dietary iron and slow bowel movement','Those do not describe the sickling mechanism.'],['Guaranteed elimination of infection risk','Sickle cell disease can increase infection risk.']]),
 q('In the simplified HbSS inheritance model, what causes sickle cell anemia?','Two HbS alleles','Two HbS alleles produce HbSS sickle cell anemia. Other inherited combinations can also cause forms of sickle cell disease.',[['One HbA allele with one HbS allele always causes HbSS','That combination is usually sickle cell trait.'],['An acquired lack of intrinsic factor','That causes a B12-absorption problem.'],['A high thyroid hormone result','That does not determine globin inheritance.']]),
 q('Why can a sickle-cell pain crisis cause severe pain?','Vaso-occlusion reduces oxygen delivery to tissues','Blocked flow causes ischemia. This is different from pain caused only by low nutrient intake.',[['Rigid RBCs always improve microcirculation','Rigid cells contribute to impaired flow.'],['HbS removes every nerve in the area','That is not the pain mechanism.'],['Pain rules out vessel blockage','Vessel blockage can cause ischemic pain.']],'Apply'),
 q('Why may hydroxyurea reduce sickling complications?','It can increase fetal hemoglobin','Higher HbF interferes with HbS polymerization and helps reduce sickling-related events.',[['It is only an antihistamine','Hydroxyurea is not an allergy antihistamine.'],['It increases iodine uptake','That is not its sickle-cell effect.'],['It directly removes all HbS genes from every patient','It does not universally erase the inherited mutation.']],'Apply'),
 q('A sickle-cell patient develops new chest symptoms and breathing difficulty. Which complication needs urgent consideration?','Acute chest syndrome','Acute chest syndrome is a serious sickle-cell complication involving new pulmonary disease. Breathing symptoms require prompt clinical assessment.',[['Pica as the only explanation','Pica does not explain an acute pulmonary complication.'],['A harmless proof that all vessels are open','Respiratory symptoms can signal a serious complication.'],['A guaranteed isolated absence seizure','The described problem is pulmonary, not a brief staring spell.']],'Apply')
 ],{update:'Clinical update: a blanket “no cure” statement is outdated. Stem-cell transplantation can be curative for some patients, and gene therapies are options for selected patients.',ref:{label:'NHLBI · Sickle cell treatment',url:'https://www.nhlbi.nih.gov/health/sickle-cell-disease/treatment'}}),
 lesson('a7','Thalassemia & the anemia comparison','27–32','Thalassemia makes too little of a globin chain. Iron deficiency makes too little hemoglobin because iron is missing.',[
 section('The chain-production problem','Adult hemoglobin normally uses alpha and beta globin chains. In thalassemia, inherited changes reduce or prevent production of one chain type. Unbalanced chains damage developing cells, so both ineffective production and increased RBC destruction can occur. Cells are usually microcytic and hypochromic. Small cells alone therefore do not prove iron deficiency.'),
 section('Why the spleen, bones, and iron can be affected','The marrow may expand as it tries to make more cells, contributing to skeletal changes in severe disease. The spleen can enlarge because of increased cell breakdown and blood formation outside normal marrow. Repeated transfusions bring iron into the body; increased absorption can also contribute to iron overload. Excess iron can harm organs.'),
 section('Connect the treatment with the mechanism','Severe disease may require regular transfusion. Iron chelation binds excess iron so it can be removed; it does not mean the patient needs extra iron. Hemoglobin studies and genetic testing help distinguish thalassemia from other microcytic disorders. Management depends on type and severity. Mild carrier states differ substantially from transfusion-dependent disease. Compare: iron deficiency = depleted building material; B12 deficiency = defective DNA synthesis; aplastic anemia = failing marrow; hemolysis = shortened cell survival; thalassemia = reduced globin-chain production.')
 ],['Reduced globin-chain synthesis','Unbalanced chains','Ineffective production & hemolysis','Microcytic anemia'],'Sickle: abnormal chain structure. Thalassemia: reduced chain production.',[
 ['Globin chain','A protein chain that forms part of hemoglobin.','Reduced alpha or beta chain production produces different thalassemia types.'],
 ['Chelation','Using a medicine that binds excess metal such as iron for removal.','It addresses iron overload, often associated with repeated transfusions.'],
 ['Splenomegaly','Enlargement of the spleen.','In severe thalassemia, cell breakdown and abnormal blood formation can contribute.']
 ],[
 q('What is the central defect in thalassemia?','Reduced or absent synthesis of an alpha or beta globin chain','The imbalance harms developing RBCs and shortens survival. It is different from HbS, which involves altered chain structure.',[['Always loss of intrinsic factor','That is a B12-malabsorption mechanism.'],['Only depleted dietary iron','Iron deficiency is a different cause of microcytosis.'],['Only a loss of sympathetic tone','That is a neurogenic-shock mechanism.']]),
 q('Which RBC pattern is common in thalassemia?','Microcytic and hypochromic','Reduced effective hemoglobin production produces small, relatively pale cells. This pattern overlaps iron deficiency, so further testing matters.',[['Only macrocytic cells in every case','Thalassemia usually has a microcytic pattern.'],['No RBC changes are possible','RBC appearance and hemoglobin production can be abnormal.'],['A CD4 count below 200 alone','That is not an RBC size or color pattern.']]),
 q('What is the purpose of iron chelation?','Remove excess iron','Chelators bind iron and aid its removal. Repeated transfusions can cause overload; adding iron without assessing deficiency can be inappropriate.',[['Provide extra dietary iron to everyone','Chelation addresses excess, not deficiency.'],['Increase every beta-globin gene','Chelation does not directly restore globin gene synthesis.'],['Treat a prolonged seizure as first-line rescue','It is not a seizure rescue treatment.']]),
 q('Why can severe thalassemia cause bone changes?','Marrow expansion occurs in an attempt to increase blood-cell production','Ineffective production drives a strong replacement response. Expanded marrow can alter the skeleton in severe disease.',[['All thyroid hormone is missing','That is not the main explanation here.'],['Bones contain no marrow','Marrow is located within bones.'],['Bone deformity is explained only by thyroid hormone excess','In severe thalassemia, attempts to compensate through marrow expansion can alter bone structure.']],'Apply'),
 q('A repeatedly transfused patient with thalassemia has iron overload. Why is that possible?','Each transfusion adds iron that can accumulate','The body has limited ways to remove excess iron. Over time, repeated transfusions can create a clinically important burden.',[['Transfused RBCs contain no iron','Hemoglobin in RBCs contains iron.'],['Iron overload proves transfusions never occurred','Transfusions are a major possible source.'],['Chelation is intended to add still more iron','Chelation aims to remove excess iron.']],'Apply'),
 q('Which comparison is correct?','Iron deficiency and thalassemia can both have low MCV, but different causes','Small cells are a pattern, not a complete diagnosis. Iron studies and hemoglobin-related testing help distinguish depleted iron from globin-production disorders.',[['Low MCV always proves iron deficiency','Thalassemia and other disorders can also lower MCV.'],['Thalassemia is the same as intrinsic-factor deficiency','These have different mechanisms.'],['Sickle cell and thalassemia always have identical globin defects','One involves HbS structure; the other involves chain production.']],'Apply')
 ])
 ]
});
