// All questions are curated from the supplied course topics. Answer order is shuffled in the UI.
const q = (prompt, answer, explanation, wrong, level = 'Understand') => ({prompt, answer, explanation, wrong, level});
const section = (title, text) => ({title,text});
const lesson = (id,title,pages,key,sections,flow,memory,terms,questions,extra={}) => ({id,title,pages,key,sections,flow,memory,terms,questions,...extra});
export const COURSE = [
{
 id:'shock', title:'Shock', label:'Circulation & perfusion', week:'Week 1', icon:'activity', color:'#007f78', source:'sources/shock-slides.pdf',
 description:'Understand what fails when the tissues do not receive the blood flow they need.',
 lessons:[
 lesson('s1','Blood flow & oxygen delivery','2–6','Shock is inadequate tissue perfusion. Blood pressure is only one clue.',[
 section('Start with the delivery system','Blood carries oxygen and nutrients to cells. Perfusion means blood actually reaches the tissues. For adequate delivery, the body needs enough circulating volume, an effective heart pump, and vessels that direct flow appropriately. Shock happens when this system cannot meet cellular needs. It is a physical circulation problem, not simply the emotional feeling of being shocked.'),
 section('Three numbers, in plain language','Cardiac output (CO) is how much blood the heart pumps each minute. CO = heart rate (HR) × stroke volume (SV). Heart rate counts beats per minute; stroke volume is blood pumped per beat. Mean arterial pressure (MAP) is the average driving pressure in arteries. Systemic vascular resistance (SVR) is the resistance the heart pumps against. The slides also use PVR to mean peripheral vascular resistance; elsewhere PVR can mean pulmonary vascular resistance, so read the context.'),
 section('A worked example','At 80 beats/min and 70 mL/beat, CO is 5,600 mL/min, or 5.6 L/min. If stroke volume falls, the heart may beat faster to maintain output. For a typical resting rhythm, estimated MAP = (systolic pressure + 2 × diastolic pressure) ÷ 3. A pressure of 120/60 gives an estimated MAP of 80 mmHg. These formulas explain relationships; they do not diagnose shock by themselves.')
 ],['Circulating volume','Heart pumps blood','Vessels guide flow','Tissues receive oxygen'],'Think: enough volume + a working pump + appropriate vessel tone.',[
 ['CO','Cardiac output: the volume of blood pumped each minute.','CO = HR × SV, so either a slow rate or a low volume per beat can reduce flow.'],
 ['MAP','Mean arterial pressure: the average pressure driving systemic blood flow.','A pressure reading helps assess circulation, but early shock may still have a normal pressure.'],
 ['SVR','Systemic vascular resistance: opposition to blood flow through the systemic vessels.','Vasoconstriction usually raises resistance; vasodilation lowers it.']
 ],[
 q('What is the central problem in shock?','Inadequate tissue perfusion','The defining problem is insufficient blood flow to meet the tissues’ oxygen and nutrient needs. Hypotension is common later, but it is not required for early shock.',[['Feeling startled','Emotional shock is different from circulatory shock.'],['A high hemoglobin level','Hemoglobin affects oxygen transport, but a high level does not define shock.'],['Increased thyroid hormone','Thyroid excess may affect circulation, but it is not the definition of shock.']]),
 q('Which relationship calculates cardiac output?','Heart rate × stroke volume','The heart beats a certain number of times each minute and ejects a volume each beat. Multiplying the two gives volume per minute.',[['Heart rate ÷ stroke volume','Division does not give the volume pumped each minute.'],['Blood pressure × temperature','Neither factor counts the blood ejected with each beat.'],['Hemoglobin × platelet count','These are blood components, not the two factors in cardiac output.']]),
 q('Widening systemic arterioles usually has which effect?','Decreased systemic vascular resistance','A wider vessel offers less opposition to flow. If vasodilation is widespread, arterial pressure may fall and blood may be distributed poorly.',[['Increased systemic vascular resistance','Narrowing vessels, rather than widening them, usually increases resistance.'],['Immediate destruction of all red blood cells','Vessel width does not directly destroy all circulating red cells.'],['No possible effect on circulation','Vessel tone is a major part of circulatory regulation.']]),
 q('HR is 100 beats/min and SV is 50 mL/beat. What is CO?','5 L/min','100 × 50 = 5,000 mL/min. Dividing by 1,000 converts milliliters into 5 liters per minute.',[['0.5 L/min','This loses a factor of ten during calculation or conversion.'],['50 L/min','5,000 mL is 5 L, not 50 L.'],['2 L/min','Dividing 100 by 50 does not calculate cardiac output.']],'Apply'),
 q('Using the usual resting estimate, what is MAP for BP 90/60 mmHg?','70 mmHg','MAP ≈ (90 + 2 × 60) ÷ 3 = 210 ÷ 3 = 70 mmHg. Diastole receives twice the weight in this estimate.',[['75 mmHg','75 is the simple average, which does not weight diastole twice.'],['30 mmHg','30 is pulse pressure, the difference between systolic and diastolic pressure.'],['150 mmHg','Adding the two pressures is not the MAP estimate.']],'Apply'),
 q('After bleeding, a patient has normal BP but tachycardia and low urine output. Which interpretation fits?','Early compensated shock is possible','The body can temporarily maintain pressure by increasing rate and constricting vessels. Low urine output suggests impaired kidney perfusion, so normal BP does not exclude shock.',[['Shock is impossible with normal BP','Compensation can preserve BP early.'],['Normal BP proves kidney perfusion is adequate','The kidneys may receive reduced blood flow despite a normal pressure.'],['Only thyroid disease can cause tachycardia','Compensation after blood loss is another cause.']],'Apply')
 ]),
 lesson('s2','What happens to cells & organs','7, 11, 38','Less oxygen means less usable energy. Compensation can hide the problem only temporarily.',[
 section('Why oxygen matters','Cells normally make much of their adenosine triphosphate (ATP), their usable energy supply, through aerobic metabolism. When oxygen delivery falls, they rely more on anaerobic pathways, produce less ATP, and may accumulate lactate and acid. An elevated lactate is an important clue in context, but it is not unique to shock.'),
 section('Why swelling and damage follow','The sodium–potassium pump uses ATP to move sodium out of cells and potassium into cells. Energy failure impairs the pump. Sodium accumulates inside, water follows, and cells swell. Prolonged hypoperfusion injures membranes, disrupts function, and promotes inflammation. Continued damage can progress to multiple organ dysfunction.'),
 section('The three teaching stages','In compensated shock, protective responses may maintain BP while the pulse rises, urine decreases, and the patient becomes anxious. In progressive shock, those responses are no longer enough: hypotension, worsening confusion, low urine output, and organ injury appear. The slides call the final stage irreversible shock, with severe damage that no longer responds effectively to treatment. These are teaching categories, not a reason to wait for a later stage.')
 ],['Low tissue oxygen','Less ATP','Ion pumps fail','Cell injury','Organ dysfunction'],'Low flow → low oxygen → low energy → cell injury.',[
 ['ATP','Adenosine triphosphate: the cell’s readily usable energy supply.','Membrane pumps and many other processes need ATP.'],
 ['Hypoperfusion','Too little blood flow reaching a tissue.','It can impair kidney function, brain function, and other organs before profound hypotension appears.'],
 ['LOC','Level of consciousness: how awake and responsive a person is.','A falling LOC may reflect impaired brain perfusion or other serious problems.']
 ],[
 q('Why does inadequate oxygen delivery threaten cells?','ATP production becomes insufficient','Oxygen supports efficient energy production. When energy becomes inadequate, pumps and other essential cellular functions fail.',[['Cells no longer need nutrients','Cells still need nutrients, but delivery and energy production are impaired.'],['ATP production becomes unlimited','Anaerobic pathways produce less ATP, not unlimited ATP.'],['All organs immediately improve','Hypoperfusion damages organ function.']]),
 q('Why can cells swell during prolonged hypoperfusion?','Pump failure allows sodium and water to accumulate inside','The sodium–potassium pump needs ATP. Without enough energy, intracellular sodium rises and water follows by osmosis.',[['Water cannot enter any cell','Water can move across cell membranes.'],['The pump makes too much ATP','The pump consumes ATP; it does not manufacture it.'],['All intracellular sodium is removed faster','Energy failure makes sodium removal less effective.']]),
 q('Which pattern suggests progressive shock?','Falling BP with worsening confusion and very low urine output','This combination suggests compensation is failing and organ perfusion is worsening. It requires prompt recognition and intervention.',[['Stable mental status with improving urine output','Those changes suggest improvement, not progression.'],['A normal pulse alone','One normal value cannot establish the stage.'],['A mildly enlarged thyroid alone','That is not a defining progressive-shock pattern.']]),
 q('Why might lactate rise in shock?','Impaired oxygen delivery can increase anaerobic metabolism','Low perfusion can reduce oxygen availability and favor lactate accumulation. Lactate must be interpreted with the overall clinical picture.',[['Lactate is a direct count of platelets','Lactate is a metabolic molecule, not a cell count.'],['Lactate only rises in HIV','Many conditions can raise lactate.'],['Anaerobic metabolism always produces more ATP than aerobic metabolism','Anaerobic pathways produce much less ATP per glucose.']],'Apply'),
 q('A patient becomes more confused as shock worsens. What is the most relevant connection?','Brain function may deteriorate when perfusion falls','The brain needs a continuous supply of oxygen and nutrients. Reduced delivery can cause altered consciousness, although clinicians also assess other causes.',[['Confusion proves the patient is exaggerating','Confusion can be an objective sign of organ dysfunction.'],['The brain does not need oxygen','Brain cells depend on oxygen and metabolic fuel.'],['Confusion guarantees a generalized seizure','Altered consciousness has several possible causes.']],'Apply'),
 q('Which trend best supports recovery of organ perfusion?','Mental status and urine output improve','Better brain responsiveness and kidney output support improved organ perfusion when assessed alongside circulation and other findings.',[['Urine output keeps falling','Falling output can indicate worsening perfusion.'],['New acidosis and declining consciousness','These changes raise concern for deterioration.'],['Severe hypotension persists unchanged','Persistent hypotension does not support recovery.']],'Apply')
 ]),
 lesson('s3','The body’s compensation systems','4, 8–10','The sympathetic nervous system acts quickly; RAAS helps conserve volume.',[
 section('The fast response: SNS','The sympathetic nervous system (SNS) is the body’s rapid fight-or-flight system. It increases heart rate and contractility and promotes vasoconstriction in many vessels. Norepinephrine and epinephrine help drive these responses. Blood is preferentially directed toward vital organs, which can explain cool skin and reduced gut activity in many low-output forms of shock.'),
 section('The volume response: RAAS','The renin–angiotensin–aldosterone system (RAAS) activates when the kidneys sense inadequate perfusion. Renin helps generate angiotensin II, which constricts vessels. Aldosterone encourages sodium retention; water follows the sodium. Antidiuretic hormone (ADH) also helps conserve water. Together, these responses attempt to increase circulating volume and pressure.'),
 section('Helpful first, harmful if the cause persists','Compensation buys time; it does not stop bleeding, repair damaged heart muscle, or remove an obstruction. In cardiogenic shock, vasoconstriction increases afterload, the resistance against which the failing heart must eject blood. Retaining fluid can also worsen congestion. Always connect a response with both its short-term benefit and its possible cost.')
 ],['Reduced kidney perfusion','Renin release','Angiotensin II','Aldosterone','Sodium & water retention'],'SNS: faster and tighter. RAAS: tighter and retain.',[
 ['SNS','Sympathetic nervous system: rapid autonomic responses that support circulation.','It can increase rate, contractility, and vascular tone.'],
 ['RAAS','Renin–angiotensin–aldosterone system: a hormonal system that supports pressure and volume.','Angiotensin II constricts vessels; aldosterone promotes sodium retention.'],
 ['Afterload','The resistance the ventricle must overcome to eject blood.','More resistance can make a damaged heart work harder.']
 ],[
 q('Which is a typical sympathetic response to falling perfusion?','Increased heart rate and vasoconstriction','These changes attempt to preserve cardiac output and arterial pressure. They are common compensatory responses, although some shock types behave differently.',[['Universal bradycardia and vasodilation','This is not the typical intact sympathetic response.'],['Immediate removal of all circulating fluid','Compensation attempts to preserve circulation, not empty it.'],['Decreased heart contractility in every patient','SNS activation generally increases contractility.']]),
 q('What is a major effect of aldosterone?','Increased sodium retention, with water following','Aldosterone acts on the kidneys to retain sodium. This can help increase circulating volume.',[['Destruction of hemoglobin','That is not aldosterone’s main function.'],['Direct conversion of RNA into DNA','That is an enzyme action associated with retroviruses.'],['Guaranteed rapid diuresis','Aldosterone promotes retention rather than increased fluid loss.']]),
 q('Which substance in RAAS promotes vasoconstriction?','Angiotensin II','Angiotensin II helps raise vascular tone. It also promotes aldosterone release, linking pressure support with fluid retention.',[['Intrinsic factor','Intrinsic factor supports dietary vitamin B12 absorption.'],['Thyroxine-binding globulin','This transports thyroid hormone in blood.'],['Bilirubin','Bilirubin is a product of heme breakdown.']]),
 q('Why may vasoconstriction become harmful in cardiogenic shock?','It raises the workload of an already failing pump','Higher systemic resistance means higher afterload. A damaged heart may struggle to eject against it, worsening low output and oxygen demand.',[['It repairs damaged heart muscle immediately','Vasoconstriction does not repair myocardium.'],['It always makes the heart’s work zero','Higher resistance usually increases the pumping burden.'],['It removes a pulmonary embolus','Vascular constriction does not remove an obstruction.']],'Apply'),
 q('Why may a patient with low-output shock have cool, clammy skin?','Blood is redirected away from skin during compensation','Peripheral vasoconstriction can reduce skin perfusion while the body attempts to support vital organs. This finding is common but not universal across shock types.',[['All shock types always have hot, dry skin','Skin patterns differ, especially in distributive shock.'],['The skin is making excessive hemoglobin','Hemoglobin is inside red cells, not produced as a skin response.'],['RAAS prevents any vascular changes','RAAS includes vasoconstrictor effects.']],'Apply'),
 q('Why can urine output fall during compensation?','Reduced kidney perfusion and hormone-mediated water conservation','The kidneys receive less effective flow and retention systems conserve fluid. Low output is therefore an important trend to assess.',[['Urine output is unrelated to circulation','Kidney function is closely related to perfusion.'],['The kidneys are necessarily destroyed permanently','Early reductions can improve when the cause is treated.'],['Aldosterone always causes major water loss','Its sodium-retaining effect tends to conserve water.']],'Apply')
 ]),
 lesson('s4','Hypovolemic shock: too little volume','13–16','A pump cannot eject enough blood when too little blood returns to fill it.',[
 section('Trace the mechanism','Hypovolemic shock begins with a loss of circulating volume. Blood loss, severe vomiting or diarrhea, and plasma loss after burns are examples. Third spacing means fluid moves out of the useful circulating space into tissues or another body compartment. Less volume returns to the heart, reducing preload, stroke volume, cardiac output, and tissue perfusion.'),
 section('Why the signs fit','The heart often speeds up to compensate. The skin may become cool and clammy because vessels constrict. Thirst, reduced urine, anxiety, and a weak pulse may appear. Blood pressure may initially remain normal and fall later. The key is the pattern and trend, especially when there is a clear source of blood or fluid loss.'),
 section('Treatment follows the missing component','The clinical team controls the cause and restores circulation with appropriate fluids and, for significant bleeding, blood products as indicated. Oxygen and close monitoring support care. Vasopressors do not replace missing blood volume or stop hemorrhage; they are used when clinically indicated alongside resuscitation. Reassess breathing, BP, pulse, consciousness, urine output, and signs of fluid overload. Positioning is individualized; routine steep head-down Trendelenburg should not be memorized as a universal treatment.')
 ],['Volume loss','Less venous return','Less preload','Lower stroke volume','Lower cardiac output'],'Hypo-volume = not enough circulating fluid.',[
 ['Preload','Ventricular filling and stretch before a contraction.','Reduced venous return generally reduces preload.'],
 ['Third spacing','Fluid shifts out of the effective circulation into tissues or another compartment.','The body may contain fluid while the circulating vessels are relatively depleted.'],
 ['Hemorrhage','Bleeding or loss of blood.','Replacing volume must be paired with identifying and controlling the bleeding source.']
 ],[
 q('Which event can directly cause hypovolemic shock?','Major gastrointestinal blood loss','Bleeding reduces circulating volume. The resulting fall in venous return and stroke volume can cause inadequate tissue perfusion.',[['An isolated brief absence seizure','This does not inherently remove circulating volume.'],['High TSH without fluid loss','A hormone result alone does not establish volume depletion.'],['HIV antibodies without circulatory impairment','An antibody test alone is not a hypovolemic cause.']]),
 q('What usually happens first in the hypovolemic mechanism?','Reduced circulating volume and venous return','Less blood comes back to fill the heart. Reduced filling then lowers stroke volume and can lower cardiac output.',[['Increased circulating volume','That contradicts the primary volume deficit.'],['Guaranteed increased preload','Reduced venous return usually lowers preload.'],['Immediate increased hemoglobin production','New red-cell production cannot immediately replace lost blood.']]),
 q('What is the main treatment principle?','Control the loss and restore appropriate circulating volume','Resuscitation addresses the deficit, while treatment of the cause prevents continued loss. Monitoring checks whether perfusion improves and complications develop.',[['Use vasoconstriction as a substitute for stopping bleeding','Increasing tone does not control hemorrhage or replace lost volume.'],['Avoid assessing the source of fluid loss','The cause determines the necessary treatment.'],['Replace thyroid hormone in every case','Thyroid replacement does not correct an ordinary volume deficit.']]),
 q('Severe vomiting and diarrhea are followed by a fast pulse, low BP, and oliguria. Which shock mechanism best fits?','Hypovolemic','Substantial gastrointestinal fluid loss can reduce effective circulating volume. The fast pulse and low urine output fit attempts to compensate and impaired perfusion.',[['Cardiogenic because the heart is always the original problem','The history points to fluid loss, not primary pump failure.'],['Neurogenic because the pulse is fast','Neurogenic shock commonly has relative bradycardia with lost sympathetic tone.'],['Obstructive because diarrhea physically blocks the heart','Diarrhea does not create a mechanical blockage in central circulation.']],'Apply'),
 q('After major bleeding, why might a vasopressor alone be insufficient?','It increases vessel tone without replacing lost blood volume','An underfilled circulation still lacks adequate volume. Treatment must address bleeding and the resuscitation needs, with vasoactive support only as indicated.',[['It always replaces all missing red blood cells','A vasoactive drug is not a blood transfusion.'],['It directly closes every bleeding vessel','Systemic vasoconstriction is not definitive hemorrhage control.'],['Volume has no role in venous return','Volume is essential to filling and output.']],'Apply'),
 q('Which improvement would support an effective response to resuscitation?','Improving urine output with clearer consciousness','These changes suggest better organ perfusion when considered with BP, pulse, breathing, and other findings. A single reading is less useful than a coherent trend.',[['Progressively weaker pulse and reduced responsiveness','These are concerning signs of deterioration.'],['New breathing difficulty after excessive fluids','This may indicate a complication such as fluid overload.'],['No need to reassess any vital signs','Ongoing reassessment is central to shock care.']],'Apply')
 ]),
 lesson('s5','Cardiogenic & obstructive shock','17–24','Cardiogenic means pump failure. Obstructive means a barrier to central blood flow.',[
 section('Cardiogenic: the pump cannot keep up','A myocardial infarction (MI, heart attack), serious dysrhythmia, or structural heart damage can reduce pumping. Contractility means the strength of contraction. Low contractility lowers stroke volume and cardiac output. Blood may back up into the lungs, producing pulmonary edema, breathlessness, and hypoxemia even though the body is not missing blood volume.'),
 section('Obstructive: the route is blocked','A major pulmonary embolism (PE, a clot obstructing pulmonary circulation), cardiac tamponade (fluid compressing the heart), or tension pneumothorax (pressurized air impairing chest circulation) can prevent effective blood flow. The heart may be capable of contracting, but filling or outflow is obstructed. Raised jugular venous pressure may be a clue. Not every uncomplicated pneumothorax causes shock.'),
 section('Match treatment to the failure','For cardiogenic shock, care aims to treat the cardiac cause, support output and oxygen delivery, and avoid worsening congestion. Fluids are assessed cautiously; medications and selected mechanical support may be used. The slides mention an intra-aortic balloon pump (IABP), an example of mechanical support rather than a treatment for every patient. Obstructive shock requires urgent treatment of the obstruction, such as drainage of tamponade, treatment of a major PE, or emergency decompression of tension pneumothorax by trained clinicians.')
 ],['Pump failure or obstruction','Lower effective cardiac output','Lower organ perfusion','Cause-specific treatment'],'Pump problem = cardiogenic. Path blocked = obstructive.',[
 ['MI','Myocardial infarction: heart muscle injury caused by interrupted blood supply.','Damaged muscle may contract inadequately and reduce output.'],
 ['PE','Pulmonary embolism: material, usually a blood clot, obstructing pulmonary circulation.','A sufficiently severe obstruction can reduce output and cause shock.'],
 ['Pulmonary edema','Fluid accumulation in the lungs.','It can occur when a failing left ventricle causes pressure to back up into pulmonary vessels.']
 ],[
 q('Which description defines cardiogenic shock?','Primary cardiac pump failure with inadequate tissue perfusion','The heart cannot generate adequate effective output. This can occur despite an adequate circulating blood volume.',[['All shock after blood loss','That describes hypovolemia.'],['Any severe allergic reaction','That points to anaphylactic distributive shock.'],['Loss of sympathetic tone after spinal injury','That points to neurogenic distributive shock.']]),
 q('Which is a classic obstructive cause?','Cardiac tamponade','Fluid under pressure around the heart can limit filling. Removing the obstruction addresses the mechanism.',[['Dietary iron deficiency','This reduces hemoglobin production rather than mechanically obstructing circulation.'],['Hashimoto thyroiditis','This is autoimmune thyroid disease.'],['Aplastic anemia','This is impaired bone marrow production.']]),
 q('Why may pulmonary edema appear in cardiogenic shock?','Blood backs up when the heart cannot pump effectively','Pressure can rise upstream in pulmonary vessels and fluid can move into lung tissue. Low output and congestion can coexist.',[['The body always loses every liter of fluid','Cardiogenic shock is not defined by severe external fluid loss.'],['The lungs no longer contain blood vessels','Pulmonary vessels are present and can become congested.'],['Viral RNA directly turns into lung water','This is not the cardiogenic mechanism.']]),
 q('A patient develops low BP and pulmonary edema after an MI. Which mechanism is most likely?','Cardiogenic pump failure','The trigger is damaged myocardium. Pulmonary congestion together with low perfusion fits a weak pump rather than an isolated volume deficit.',[['Hypovolemia proved by pulmonary edema','Edema does not prove a lack of circulating volume.'],['Neurogenic shock proved by the MI','MI is a cardiac injury, not loss of spinal sympathetic signaling.'],['Anaphylaxis without any allergic exposure or signs','The described cause and pattern favor cardiac failure.']],'Apply'),
 q('A tension pneumothorax causes shock. Which principle addresses the cause?','Urgently relieve the mechanical obstruction','Pressurized air can interfere with venous return and effective cardiac output. Skilled emergency treatment relieves that pressure.',[['Only give iron supplements','Iron does not relieve chest pressure.'],['Only increase thyroid hormone','Thyroid hormone does not remove the obstruction.'],['Wait until the kidneys stop producing urine','Delaying treatment risks further organ injury.']],'Apply'),
 q('Why are large fluid loads assessed cautiously in cardiogenic shock?','They can worsen congestion in a failing heart','The problem may be inadequate pumping rather than missing volume. Additional fluid can increase pulmonary congestion, so treatment is guided by careful assessment.',[['All fluids are forbidden in every possible case','Some patients may need carefully assessed fluids; the rule is not absolute.'],['Fluids always cure damaged myocardium','Fluids do not repair heart muscle.'],['Cardiogenic shock is always caused by diarrhea','The defining cause is pump failure.']],'Apply')
 ]),
 lesson('s6','Neurogenic & anaphylactic shock','25–32','Both can lower vascular tone, but their triggers and distinguishing signs differ.',[
 section('Distributive means poorly distributed','In distributive shock, widespread vasodilation and sometimes capillary leakage reduce effective circulation. The vessels are too relaxed or leaky for blood to be distributed appropriately. The total body fluid amount may not initially be low, but effective filling and perfusion can fall.'),
 section('Neurogenic: the sympathetic signal is lost','High spinal cord injury or spinal anesthesia can interrupt sympathetic vascular control. Vessels dilate, BP falls, and the usual compensatory increase in heart rate may be absent. Relative bradycardia with hypotension and warm skin is a useful distinguishing pattern. Temperature regulation can also be impaired. Care supports pressure, heart rate, temperature, and the underlying injury.'),
 section('Anaphylactic: a rapid severe allergic response','Mast-cell mediators such as histamine cause vasodilation, leakage, airway swelling, and bronchospasm. A trigger may be a medication, food, or insect sting. Hypotension with wheeze, lip or tongue swelling, or hives is highly concerning, though skin signs can be absent. Intramuscular epinephrine is first-line treatment; airway support and appropriate fluids may be needed. Antihistamines and corticosteroids are adjuncts, not substitutes for epinephrine.')
 ],['Loss of tone or allergic mediators','Vasodilation ± leakage','Reduced effective circulation','Cause-specific support'],'Neurogenic: slow pulse, lost tone. Anaphylactic: allergy, airway, epinephrine.',[
 ['Bradycardia','A slower-than-expected heart rate.','It can help distinguish neurogenic shock from many tachycardic shock patterns.'],
 ['Angioedema','Swelling in deeper tissue, sometimes involving lips, tongue, or airway.','Airway involvement can be life-threatening in anaphylaxis.'],
 ['Bronchospasm','Tightening of airway smooth muscle.','It narrows airways and may cause wheezing and breathing difficulty.']
 ],[
 q('Which mechanism underlies neurogenic shock?','Loss of sympathetic tone causing vasodilation','Interrupted sympathetic control allows vessels to relax and may prevent the normal tachycardic response.',[['Major external bleeding is always required','Neurogenic shock can occur without major blood loss.'],['Excessive HbS polymerization','That is a sickle-cell mechanism.'],['Only mechanical blockage of the pulmonary artery','That is an obstructive mechanism.']]),
 q('Which combination is especially suggestive of neurogenic shock?','Hypotension with relative bradycardia after spinal cord injury','Loss of sympathetic control explains both reduced vascular tone and an inadequate heart-rate response. The clinical setting matters.',[['Hypertension and weight gain alone','That does not fit the defining circulatory pattern.'],['Isolated low ferritin','Low ferritin points to depleted iron stores.'],['Hives with wheeze after a drug exposure','That favors anaphylaxis.']]),
 q('Which drug is first-line for anaphylaxis?','Intramuscular epinephrine','Epinephrine supports vascular tone and helps counter airway effects. Antihistamines do not treat the full life-threatening circulatory and airway response.',[['An antihistamine alone','This may reduce some skin symptoms but is not an adequate first-line substitute.'],['Corticosteroids alone','These are adjuncts and do not replace timely epinephrine for the immediate emergency.'],['An inhaled bronchodilator alone','This may help bronchospasm but does not treat the full circulatory and upper-airway emergency.']]),
 q('Minutes after a medication, a patient develops wheezing, tongue swelling, and hypotension. What best fits?','Anaphylactic shock','The rapid exposure-related airway and circulatory changes strongly fit anaphylaxis. Prompt emergency management is required.',[['Aplastic anemia','Marrow failure does not explain a rapid allergic airway reaction.'],['An absence seizure','A brief staring episode does not explain swelling and hypotension.'],['Pernicious anemia','B12 malabsorption does not cause this immediate exposure-related pattern.']],'Apply'),
 q('Why can neurogenic shock have warm skin despite low BP?','Peripheral vessels are dilated because sympathetic tone is lost','Unlike intact compensation with peripheral constriction, lost sympathetic tone can keep skin vessels relatively dilated.',[['Low BP guarantees cold skin in every shock type','Distributive patterns can differ from low-output patterns.'],['Warm skin proves perfusion is adequate','Skin warmth does not establish adequate organ perfusion.'],['All blood has left the circulation','The main mechanism is abnormal vascular tone, not necessarily loss of blood.']],'Apply'),
 q('What is the role of antihistamines in life-threatening anaphylaxis?','Adjunctive treatment after the essential emergency measures','They can help some symptoms, but epinephrine and appropriate airway/circulatory care remain central. They should not delay first-line treatment.',[['They replace epinephrine for airway swelling','They do not adequately address the whole emergency.'],['They repair spinal cord injury','They do not reverse neurogenic injury.'],['They restore every lost red blood cell','They are not blood products.']],'Apply')
 ]),
 lesson('s7','Septic shock & watching the response','33–38','Infection can trigger an uncontrolled response that disrupts perfusion and organ function.',[
 section('The infection–inflammation connection','Sepsis is life-threatening organ dysfunction due to a dysregulated response to infection. Inflammatory mediators can dilate vessels, increase capillary leakage, and disrupt microcirculation. Septic shock is a severe subset with persistent circulatory and metabolic abnormalities. In the adult clinical definition, vasopressors are needed to maintain MAP of at least 65 mmHg and lactate remains above 2 mmol/L despite adequate volume resuscitation.'),
 section('Recognize patterns without rigid phases','The slides teach a warm phase with vasodilation and potentially higher cardiac output, and a cold phase with low output and worsening perfusion. These are useful patterns, but patients do not all follow a fixed two-stage sequence. Both gram-positive and gram-negative bacteria, and other organisms, can cause sepsis. Do not rule it out because skin is warm, fever is absent, or the organism is not gram-negative.'),
 section('Treat the infection and restore perfusion','Care includes rapid recognition, appropriate antimicrobials, source control where needed, crystalloid fluid resuscitation with reassessment, and vasoactive support when indicated. Cultures are obtained when feasible without substantially delaying treatment. Norepinephrine is the usual first-line vasopressor in adult septic shock. Monitor consciousness, urine output, pulse, BP/MAP, lactate trend, breathing, and oxygenation. Worsening organ dysfunction can involve the kidneys, lungs, heart, clotting system, and brain.')
 ],['Infection','Dysregulated inflammation','Vasodilation & leakage','Impaired perfusion','Organ dysfunction'],'Treat the source + support circulation + reassess the organs.',[
 ['Sepsis','Life-threatening organ dysfunction from a dysregulated response to infection.','It is more than simply having microbes in the blood.'],
 ['Source control','Treatment that removes or controls the focus of infection.','Examples include draining an infected collection or managing an infected device when indicated.'],
 ['Vasopressor','A medication that raises vascular tone and supports blood pressure.','It supports circulation while the underlying cause is treated.']
 ],[
 q('Which mechanism contributes to septic shock?','Inflammation causing vasodilation and capillary leakage','These changes impair effective circulation and tissue oxygen delivery. Microcirculatory dysfunction and organ injury also contribute.',[['Always isolated loss of dietary iron','That causes iron deficiency, not the defining septic mechanism.'],['Only excess intrinsic factor','Intrinsic factor relates to B12 absorption.'],['No possible role for infection','Infection is central to sepsis.']]),
 q('What does source control mean in sepsis care?','Addressing the focus of infection','Removing or controlling an infected focus can reduce the ongoing trigger. Antimicrobials and circulatory support remain important.',[['Only lowering the room temperature','Environmental cooling does not remove an infected focus.'],['Only correcting MCV','An RBC size index does not control infection.'],['Waiting for all organ failure to reverse first','Source management is part of treating the cause.']]),
 q('What is the usual first-line vasopressor for adult septic shock?','Norepinephrine','Guideline-based adult care uses norepinephrine as the usual first-line agent when vasopressor support is indicated. It does not replace treating the infection.',[['Levothyroxine','This is a thyroid replacement drug.'],['Oral vitamin B12','This treats deficiency, not septic circulatory collapse.'],['Hydroxyurea','This is used in conditions including sickle cell disease, not as a septic vasopressor.']]),
 q('A patient with pneumonia is hypotensive and confused but has warm skin. Which interpretation is appropriate?','Sepsis-related circulatory failure is still possible','Vasodilation can produce warm skin despite inadequate organ perfusion. Skin temperature alone cannot exclude shock.',[['Warm skin rules out every kind of shock','Distributive shock may have warm skin.'],['Only gram-negative organisms could be responsible','Several organism types can cause sepsis.'],['Confusion has no relationship to organ function','Altered consciousness can be an organ dysfunction sign.']],'Apply'),
 q('Why should BP, urine output, mental status, and lactate trends be assessed together?','They provide complementary clues about circulation and organ perfusion','No single number captures the whole response. Concordant improvements strengthen the interpretation; conflicting changes require reassessment.',[['One normal BP proves every organ is healthy','A normal pressure does not guarantee adequate perfusion.'],['Urine output is only a thyroid measurement','It reflects kidney function and can help assess perfusion.'],['Lactate always identifies the exact organism','Lactate is not an organism identification test.']],'Apply'),
 q('Which statement best reflects the warm/cold septic patterns in the slides?','They are teaching patterns, not a mandatory sequence in every patient','Vascular tone, cardiac output, and clinical signs vary. Rely on the full clinical picture and trends rather than expecting everyone to fit a rigid phase.',[['Every patient must complete the warm phase first','The course is variable.'],['Cold skin proves the infection has cleared','Cold skin can reflect poor perfusion.'],['Warm skin means no treatment is needed','Warmth can coexist with serious circulatory failure.']],'Apply')
 ],{update:'Clinical update: sepsis is not restricted to gram-negative bacteria, and warm/cold patterns are not fixed stages. Adult management here follows the linked guideline.',ref:{label:'SCCM · Surviving Sepsis Campaign',url:'https://www.sccm.org/clinical-resources/guidelines/guidelines/surviving-sepsis-guidelines-2021'}})
 ]
},
];
export {q,section,lesson};
