import {COURSE,lesson,section,q} from './course.mjs';
COURSE.push({
 id:'hiv',title:'HIV & AIDS',label:'Immunity & prevention',week:'Week 3',icon:'shield',color:'#3176aa',source:'sources/hiv-slides.pdf',
 description:'Understand the virus, the immune response, testing, treatment, and prevention without the common myths.',
 lessons:[
 lesson('h1','The virus, CD4 cells & transmission','2–4, 15','HIV targets the immune system. Transmission requires specific fluids and an effective exposure route.',[
 section('HIV and AIDS are different terms','Human immunodeficiency virus (HIV) is the virus. Acquired immunodeficiency syndrome (AIDS) is the most advanced stage of HIV disease, defined by severe immune impairment or specified illnesses. Having HIV does not automatically mean having AIDS. HIV-1 and HIV-2 are distinct types. HIV is a retrovirus with an RNA genome and infects cells including CD4-positive T-helper cells, which coordinate immune responses.'),
 section('Fluid plus route matters','Transmission can involve blood, semen and pre-seminal fluid, vaginal and rectal fluids, or breast milk. These fluids must reach susceptible tissue, such as a mucous membrane or damaged skin, or enter the bloodstream. Examples include some sexual exposures, shared injection equipment, and exposure during pregnancy, birth, or breastfeeding. Casual contact such as hugging, sharing a room, and ordinary shared utensils does not transmit HIV.'),
 section('Symptoms are not a transmission test','Someone can have HIV without obvious symptoms. In the absence of effective viral suppression, symptom-free infection can still be transmissible. Effective treatment changes this: people who achieve and maintain an undetectable viral load do not transmit HIV through sex, the U=U principle. Do not extend that statement to every possible route or assume HIV status from appearance. Standard precautions apply according to the exposure task, not a patient’s perceived identity.')
 ],['Specific infectious fluid','Effective entry route','Virus reaches susceptible cells'],'HIV = virus. AIDS = advanced disease. Exposure needs both fluid and route.',[
 ['HIV','Human immunodeficiency virus: the virus that can damage immune function.','A positive diagnosis is not automatically a diagnosis of AIDS.'],
 ['CD4 cell','A helper immune cell identified by its CD4 surface marker.','HIV-related loss of these cells weakens coordination of immune defense.'],
 ['U=U','Undetectable = Untransmittable for sexual transmission when viral suppression is achieved and maintained.','It describes effective ongoing treatment, not a universal statement about all routes.']
 ],[
 q('Which statement correctly distinguishes HIV from AIDS?','HIV is the virus; AIDS is its most advanced disease stage','HIV infection may be controlled with treatment and does not automatically mean advanced immune deficiency.',[['Every HIV diagnosis immediately means AIDS','Disease stage depends on immune status and specified illnesses.'],['AIDS is a different virus transmitted only by food','AIDS is a syndrome, not a food-borne virus.'],['HIV only affects RBC size','It primarily affects immune function.']]),
 q('Which cells are important targets of HIV?','CD4-positive T-helper cells','These cells help coordinate immune defense. Their loss is important in HIV-related immune impairment.',[['Only mature RBCs','Mature RBCs are not the key CD4 helper-cell targets described.'],['Only thyroid follicular cells','That is not the central immune target.'],['Only platelets','Platelets are not the key helper immune cells.']]),
 q('Which everyday contact does not transmit HIV?','Hugging','Ordinary casual contact does not provide an effective infectious fluid exposure route. Respectful care does not require social isolation.',[['Sharing contaminated injection equipment','This can provide blood-to-blood exposure.'],['An effective exposure to infectious blood through a needle','This can create a transmission risk.'],['Exposure through breast milk','This is a recognized possible route.']]),
 q('A person has no symptoms. What can be concluded about HIV status from appearance alone?','Nothing definitive; testing is needed','HIV can be asymptomatic. Symptoms also overlap other illnesses, so appearance cannot establish infection status.',[['No symptoms prove the person has no HIV','Asymptomatic infection is possible.'],['No symptoms prove AIDS','The absence of symptoms does not establish advanced disease.'],['A person’s social identity is an adequate diagnostic test','Diagnosis requires appropriate testing.']],'Apply'),
 q('A patient with HIV maintains an undetectable viral load on treatment. What does U=U mean?','They do not transmit HIV through sex while suppression is maintained','This is an evidence-based sexual-transmission principle. Continued treatment and monitoring matter.',[['They are cured and can stop ART','Suppression is not eradication of HIV.'],['Every conceivable exposure route is proven risk-free','The statement should not be generalized to all routes.'],['Their immune system can never improve','Treatment can support immune recovery.']],'Apply'),
 q('Why should standard precautions be based on the care task for every patient?','Potential exposure is managed without guessing infection status from appearance','Blood and other relevant exposures require appropriate protection whether or not a diagnosis is known. This supports safe, non-stigmatizing care.',[['Only patients who look ill need precautions','Appearance does not establish infection status.'],['Hugging requires the same precautions as a needlestick exposure','Routes and tasks have different exposure risks.'],['A known HIV diagnosis requires avoiding all social contact','Ordinary casual contact does not transmit HIV.']],'Apply')
 ],{ref:{label:'CDC · How HIV spreads',url:'https://www.cdc.gov/hiv/causes/index.html'}}),
 lesson('h2','Replication: how the virus copies itself','4–7, 13','Reverse transcriptase, integrase, and protease perform different jobs.',[
 section('Enter and copy the genetic message','HIV attaches to receptors on a susceptible cell and enters. Its genetic material is ribonucleic acid (RNA). Reverse transcriptase makes a deoxyribonucleic acid (DNA) copy from the viral RNA. This is the reverse of the usual direction emphasized in the course. Integrase then inserts viral DNA into the host cell’s DNA, creating a persistent viral template.'),
 section('Use the cell to make components','The integrated DNA can be transcribed into RNA. RNA provides messages for translation, the production of viral proteins, and also supplies genomes for new particles. Some proteins are initially made as long polyproteins. Protease cleaves these into functional components. Viral material is assembled and released, and protease-dependent maturation creates infectious particles.'),
 section('The eight steps are a teaching map','The slides list attachment, internalization, reverse transcription, integration, transcription, translation, cleavage, and assembly/release. Use this map to learn each job. Actual late replication processes overlap: maturation accompanies or follows budding, so do not interpret the slide’s last steps as a perfectly rigid stopwatch sequence. Antiretroviral drug classes target different processes, which explains why combined mechanisms are useful.')
 ],['Attachment & entry','RNA copied into DNA','Integration into host DNA','Protein production & new particles'],'Reverse transcriptase copies; integrase inserts; protease cuts.',[
 ['Reverse transcriptase','An enzyme that copies HIV RNA into DNA.','It provides the DNA form that can be integrated into the cell genome.'],
 ['Integrase','An enzyme that inserts viral DNA into host DNA.','Integration helps HIV persist as a template in infected cells.'],
 ['Protease','An enzyme that cleaves viral polyproteins into functional components.','This processing contributes to maturation of infectious virus particles.']
 ],[
 q('What does reverse transcriptase do in HIV replication?','Copies viral RNA into DNA','HIV begins with an RNA genome. The DNA copy allows subsequent integration into the host genome.',[['Cuts viral polyproteins only','That is the protease role.'],['Only inserts completed viral DNA into host DNA','That is integrase’s main role.'],['Makes every CD4 cell resistant to infection','It helps the virus replicate, not protect every cell.']]),
 q('What is the main job of integrase?','Insert viral DNA into host DNA','Integration creates a viral DNA template within the cell genome. This is different from copying RNA or cutting proteins.',[['Create the original RNA-to-DNA copy','That is reverse transcriptase.'],['Only cut long viral protein chains','Protease cuts viral polyproteins; it does not insert viral DNA into the host genome.'],['Remove all HIV RNA from blood instantly','That is not integrase’s job.']]),
 q('What does protease do?','Cleaves long viral polyproteins','Protein processing supplies functional viral components and supports maturation. It does not perform RNA-to-DNA copying.',[['Insert viral DNA into host DNA','Integrase inserts viral DNA into host DNA; protease instead processes long protein chains.'],['Produce antibodies in the immune system','Protease is a viral-processing enzyme.'],['Only measure the number of CD4 cells','That is a laboratory assessment.']]),
 q('Which process directly precedes integration in the course’s early replication map?','Reverse transcription producing viral DNA','The virus needs a DNA copy before integrase can insert that material into host DNA.',[['Destruction of every antibody','That is not a required lifecycle step.'],['Protease cleavage before any entry','The virus first enters and creates DNA for integration.'],['A CD4 blood-count test','A clinical test is not a viral replication step.']],'Apply'),
 q('A medicine blocks integrase. Which lifecycle job is directly targeted?','Insertion of viral DNA into host DNA','The enzyme name corresponds to integration. Other classes target entry, reverse transcription, or protein processing.',[['Only cleavage of polyproteins','That targets protease.'],['Only copying RNA into DNA','That targets reverse transcriptase.'],['Only the patient’s production of antibodies','That is not integrase’s role.']],'Apply'),
 q('Why can HIV persist after integration?','Its DNA can remain within infected cell genomes','Integrated viral DNA contributes to persistent reservoirs. Suppressing replication does not automatically remove every infected cell.',[['Integrated DNA necessarily disappears immediately after one dose','Persistence is a major reason treatment is ongoing.'],['HIV has no genetic material','HIV carries RNA and forms a DNA intermediate.'],['Protease removes every host chromosome','That is not its role.']],'Apply')
 ]),
 lesson('h3','Clinical course, CD4 & opportunistic illness','8–10','Viral load counts the virus; CD4 count reflects an important part of immune function.',[
 section('Acute infection and clinical latency','Early infection may cause fever, sore throat, rash, lymph-node enlargement, or other flu-like symptoms, though some people have no noticeable symptoms. Viral load can be high early. The subsequent chronic phase, also called clinical latency, may have few symptoms even while untreated virus continues to replicate. Latency does not mean the virus is inactive.'),
 section('Why CD4 decline matters','CD4 cells help coordinate immune defense. Without effective treatment, their number can fall and the risk of opportunistic infections and certain cancers rises. Viral load measures the amount of HIV in blood; CD4 count measures helper immune cells. These tests answer related but different questions. Effective ART usually lowers viral load and can permit immune recovery.'),
 section('AIDS is defined by immune impairment or specified illness','The adult teaching threshold is a CD4 count below 200 cells per microliter, or an AIDS-defining condition, in a person with HIV. Not every infection or nonspecific symptom is AIDS-defining. Examples include Pneumocystis jirovecii pneumonia (PJP, also called PCP) and certain malignancies such as Kaposi sarcoma. The untreated time courses shown in the slides are not inevitable outcomes today: timely effective treatment can prevent progression.')
 ],['Untreated viral replication','CD4 decline','Reduced immune defense','Opportunistic disease risk'],'Viral load = how much virus. CD4 = helper-cell defense.',[
 ['Viral load','The measured amount of HIV in blood.','Falling viral load is an important sign of effective suppression.'],
 ['Clinical latency','A chronic HIV phase with few symptoms in some people, despite ongoing untreated replication.','A person feeling well still needs care and appropriate treatment.'],
 ['Opportunistic infection','An infection that becomes more likely or severe when defenses are impaired.','Not all infections automatically qualify as AIDS-defining illnesses.']
 ],[
 q('What does HIV viral load measure?','The amount of HIV in blood','It is distinct from CD4 count, which assesses helper immune cells. Both contribute to monitoring.',[['Only the number of helper T cells','CD4 count measures helper immune cells; viral load measures the amount of virus in blood.'],['Only RBC size','MCV measures red-cell volume, which is different from the amount of HIV in blood.'],['Only the number of thyroid nodules','That is structural information.']]),
 q('What does clinical latency mean in untreated HIV?','Symptoms may be limited while the virus continues replicating','Latency in this clinical description is not complete viral inactivity. Ongoing immune damage can occur.',[['The virus is necessarily gone forever','It can remain active and persistent.'],['ART is never needed if the person feels well','Treatment is important regardless of symptoms.'],['Everyone has AIDS immediately at this stage','Disease stage depends on immune status and defining illnesses.']]),
 q('Which adult CD4 threshold is used in the teaching definition of AIDS?','Below 200 cells/µL','In a person with HIV, this degree of CD4 depletion meets an important AIDS criterion. Specified AIDS-defining illness can also establish the stage.',[['Below 2,000 cells/µL in every healthy person','That is not the teaching threshold.'],['A high viral load alone with no other criterion','Viral load is important but is not this CD4 threshold.'],['A low ferritin alone','That is not an AIDS criterion.']]),
 q('Why does CD4 depletion increase opportunistic infection risk?','Immune coordination and defense become impaired','CD4 helper cells support immune responses. Their loss leaves the body more vulnerable to specific infections and complications.',[['CD4 cells normally carry most blood oxygen','RBC hemoglobin has that role.'],['Low CD4 always increases thyroid synthesis','That is not the immune mechanism.'],['Viruses can only replicate when CD4 is high','HIV can remain active as immune damage progresses.']],'Apply'),
 q('A person with HIV has a CD4 count of 150 cells/µL. What does this meet in the adult teaching definition?','The CD4 criterion for AIDS','Below 200 cells/µL meets the severe immune-depletion criterion. Appropriate clinical management assesses the full situation.',[['Only the definition of iron deficiency','CD4 is not an iron-store test.'],['Proof that ART cannot help','Treatment can still suppress the virus and support recovery.'],['Proof of no immune impairment','The count indicates significant depletion.']],'Apply'),
 q('Why should the untreated progression timelines in the slides not be treated as inevitable?','Effective ART can prevent or greatly change progression','Modern care can suppress replication and preserve immune function. Untreated history does not predict every treated person’s outcome.',[['All people develop AIDS at exactly the same interval','Progression varies and treatment changes it.'],['ART always instantly eradicates every reservoir','Suppression is not a routine cure.'],['Symptoms alone determine viral load','Viral-load testing is needed.']],'Apply')
 ],{ref:{label:'CDC · About HIV',url:'https://www.cdc.gov/hiv/about/index.html'}}),
 lesson('h4','Testing, window periods & infant diagnosis','8, 11, 14','Different tests detect different things and become positive at different times.',[
 section('Know the target of each test','Antibody tests look for the immune response to HIV. Antigen/antibody tests also detect a viral antigen such as p24, which can appear before antibodies. Nucleic acid tests (NATs) look for viral genetic material and can often detect infection earlier. Polymerase chain reaction (PCR) is one method for amplifying genetic material; it is not simply an antibody test.'),
 section('Why an early negative can miss infection','The window period is the interval between exposure and when a particular test can detect infection. It depends on the test, specimen, and context. Typical CDC ranges are 10–33 days for NAT, 18–45 days for a laboratory antigen/antibody test using venous blood, and 23–90 days for antibody tests. These ranges are not a personal testing schedule; prevention medicines and clinical circumstances can affect interpretation. A negative result very soon after exposure may need follow-up.'),
 section('Screening and confirmation are separate','A reactive screening result needs the appropriate follow-up algorithm rather than being read in isolation. The slides show ELISA followed by Western blot, a historical sequence rather than the modern routine algorithm. Modern laboratory approaches use antigen/antibody testing and appropriate supplemental or nucleic acid tests. In young infants exposed during pregnancy, maternal antibodies can be present without the infant being infected; virologic testing is therefore important for diagnosis. CD4 count monitors immune status rather than confirming infection alone.')
 ],['Exposure','Test-specific window','Screening test','Appropriate confirmation'],'Antibody = response. Antigen = viral protein. NAT = genetic material.',[
 ['Window period','The time after exposure before a particular test can detect infection.','A very early negative may not exclude infection.'],
 ['NAT / PCR','Nucleic acid testing / polymerase chain reaction: tests or methods targeting genetic material.','They differ from tests looking for antibodies.'],
 ['Maternal antibodies','Antibodies transferred from the pregnant person to the infant.','Their presence can make antibody-only HIV diagnosis unreliable in young exposed infants.']
 ],[
 q('What does an HIV antibody test detect?','The immune response to HIV','Antibodies are made by the immune system. This differs from detecting viral proteins or genetic material directly.',[['Only viral RNA directly','That is a nucleic-acid target.'],['Only free T4','That is a thyroid hormone test.'],['Only the number of CD4 cells','That is an immune-cell count.']]),
 q('What is the window period?','The time between exposure and when a test can detect infection','Different test types become informative at different times. This explains why an early negative can require follow-up.',[['The time from AIDS diagnosis to every person’s death','That is not the testing definition.'],['A period when all viruses stop replicating','The test’s detection timing does not imply viral inactivity.'],['Only the turnaround time after the lab receives a sample','Result-processing time differs from the biological detection window.']]),
 q('Why are virologic tests important for young infants exposed to HIV?','Maternal antibodies can be present without infant infection','Antibody detection may reflect transferred maternal antibodies. Testing for the virus itself helps assess infant infection.',[['Infants cannot ever have HIV','Perinatal transmission is possible.'],['A maternal antibody guarantees the infant is infected','That conclusion is not reliable.'],['CD4 count alone always replaces all diagnostic testing','It does not by itself establish infection.']]),
 q('An antibody test is negative one day after a possible exposure. What is the correct interpretation?','It is too early to use that result alone to exclude infection','Antibody formation takes time. The exposure and test type guide appropriate follow-up and any urgent prevention assessment.',[['The result definitively excludes infection from that exposure','The test window has not passed.'],['The negative result means the person already has AIDS','A negative screen does not establish advanced disease.'],['No test timing matters','Biological detection timing matters.']],'Apply'),
 q('An initial HIV screening result is reactive. What is the next principle?','Follow the appropriate confirmatory testing pathway','A screening result is interpreted with the recommended follow-up testing. A single screen is not the whole diagnostic process.',[['Every reactive screen is ignored if there are no symptoms','Asymptomatic infection can occur.'],['CD4 count alone is always the only confirmation','Immune counts and infection diagnosis are different tasks.'],['All modern tests must always end with a Western blot','The slide sequence is historical.']],'Apply'),
 q('Which usually has an earlier detection window than an antibody-only test?','A nucleic acid test','NAT can identify viral genetic material before antibodies are detectable in many cases. Specific timing still depends on the test and context.',[['A neck examination','It does not detect HIV genetic material.'],['A blood test for ferritin','It does not diagnose HIV.'],['Waiting for AIDS symptoms instead of testing','Symptoms are not an earlier diagnostic test.']],'Apply')
 ],{update:'Clinical update: ELISA followed by Western blot is a historical teaching sequence. Use the current diagnostic pathway and test-specific windows. Infants require age-appropriate virologic testing.',ref:{label:'CDC · HIV testing',url:'https://www.cdc.gov/hiv/testing/index.html'},refs:[{label:'CDC · Clinical testing guidance',url:'https://www.cdc.gov/hivnexus/hcp/diagnosis-testing/index.html'},{label:'NIH · Infant HIV diagnosis',url:'https://clinicalinfo.hiv.gov/en/guidelines/perinatal/management-infants-diagnosis-hiv-infection-children'}]}),
 lesson('h5','ART, adherence & immune recovery','12–13, 15','Antiretroviral therapy suppresses replication; suppression is not the same as a routine cure.',[
 section('Use the correct abbreviation','ART means antiretroviral therapy. HAART is the historical term highly active antiretroviral therapy. ART uses clinician-selected combinations that act at different viral targets. A treatment may include several medicines in one tablet, and selected regimens have different drug counts. The slide’s example drug list should not be treated as a complete prescription or a universal three-drug formula.'),
 section('Understand the direction of success','The aim is to suppress viral replication, lower viral load, preserve or restore immune function, and prevent illness. With effective treatment, CD4 count can improve. Treatment is recommended promptly after diagnosis, not only after symptoms or AIDS appear. Opportunistic infections may also require treatment or preventive medicines according to immune status and other factors.'),
 section('Why consistency matters','Missed treatment can allow viral replication to rebound and contribute to resistance. Side effects and interactions need review; they are reasons to contact the care team rather than independently abandoning treatment. A sustained undetectable viral load supports health and prevents sexual transmission. It does not mean every integrated viral reservoir has disappeared, so ongoing treatment and monitoring remain essential.')
 ],['Appropriate ART','Reduced replication','Lower viral load','Immune recovery & less illness'],'ART success: virus down, defenses supported, treatment continued.',[
 ['ART','Antiretroviral therapy: medicines that suppress HIV replication.','It is not limited to one universal tablet count or drug list.'],
 ['Drug resistance','Viral changes that reduce susceptibility to a medicine.','Inadequate suppression and missed treatment can contribute to resistance.'],
 ['Viral suppression','Reduction of the amount of HIV in blood through effective treatment.','It supports health and is different from eliminating every persistent reservoir.']
 ],[
 q('What does ART stand for?','Antiretroviral therapy','HAART is an older expanded term. ART is the current general abbreviation for HIV treatment.',[['Antibody replacement testing','This is not the abbreviation.'],['Automatic renal transfusion','This is not the abbreviation.'],['Acute respiratory thyroiditis','This is not the abbreviation.']]),
 q('Which trend usually supports effective ART?','Lower viral load with preserved or improving CD4 count','Less replication means less viral burden, while immune function may recover. Trends are interpreted in clinical context.',[['Higher viral load and progressive CD4 loss','That raises concern for inadequate control.'],['Only a smaller thyroid nodule','That is not the central HIV response.'],['Only a lower MCV','RBC size does not establish viral suppression.']]),
 q('Why is adherence to ART important?','It helps maintain suppression and reduce resistance risk','Inconsistent treatment can allow replication to rebound. Medicines and appointments should be followed as prescribed.',[['Symptoms alone guarantee complete suppression','Viral-load monitoring is needed.'],['Missing medicine makes all viruses more drug-sensitive','It can instead contribute to resistance.'],['ART is only needed during fever','It is ongoing treatment, not merely symptom-based dosing.']]),
 q('An asymptomatic person receives an HIV diagnosis. What treatment principle applies?','Start appropriate ART promptly rather than waiting for AIDS','Early treatment reduces ongoing immune damage and supports long-term health. Feeling well is not a reason to delay.',[['Only treat after CD4 is zero','Waiting for extreme depletion is inappropriate.'],['No symptoms mean the virus cannot replicate','Replication can continue without symptoms.'],['Use only a slide’s example list without clinical assessment','Regimens are individualized and require professional selection.']],'Apply'),
 q('A person becomes undetectable and wants to stop ART. What should be understood?','Undetectability reflects successful suppression that generally needs ongoing treatment','Persistent reservoirs remain. Stopping treatment independently can allow rebound.',[['Undetectable always means a routine complete cure','Suppression and eradication differ.'],['There is no need for further monitoring','Follow-up remains important.'],['A better CD4 count proves no infected cells remain','CD4 recovery does not establish reservoir elimination.']],'Apply'),
 q('Why are different drug mechanisms often combined?','They target different parts of replication and help sustain suppression','Entry, reverse transcription, integration, and maturation are different processes. Appropriate combination treatment reduces the chance of uncontrolled replication.',[['All medicines must act on the same single protein','Different target classes exist.'],['Every possible three-drug list is a complete valid regimen','Not every combination is appropriate or complete.'],['Drug mechanisms have no relationship to the lifecycle','Their targets explain their roles.']],'Apply')
 ],{update:'Clinical update: ART is antiretroviral therapy. Regimens are clinician-selected combinations; the slide examples are not a universal prescription.',ref:{label:'CDC · Treating HIV',url:'https://www.cdc.gov/hiv/treatment/index.html'}}),
 lesson('h6','PrEP, PEP, pregnancy & respectful care','12, 14–15','Prevention before exposure, prevention after exposure, and treatment of established HIV have different roles.',[
 section('PrEP is before; PEP is after','Pre-exposure prophylaxis (PrEP) is medicine used by HIV-negative people to reduce the chance of acquiring HIV before potential exposure. Post-exposure prophylaxis (PEP) is emergency prevention after a possible exposure. PEP requires immediate assessment, should start as soon as possible and within 72 hours when indicated, and is usually taken for 28 days. It is not a substitute for ongoing prevention in someone with repeated exposure risk.'),
 section('Occupational exposure and perinatal prevention','After a needlestick or relevant workplace exposure, follow immediate first-aid and reporting protocols and obtain urgent assessment; do not wait for symptoms. Standard precautions reduce exposure risk. During pregnancy, effective maternal ART, appropriate monitoring, birth planning, and infant preventive treatment can greatly reduce transmission. Infant testing and feeding decisions follow local guidance and clinical context. The slides’ zidovudine example is not the whole modern prevention strategy.'),
 section('Care without stigma','Condoms and safer injection practices remain useful prevention tools. PrEP and PEP do not replace ART for established infection. U=U concerns sustained suppression and sexual transmission; it is not a reason to guess at breastfeeding or needle-sharing risk. Explain facts without blame, protect confidentiality, and treat the person with dignity. Casual contact does not justify exclusion from ordinary community life.')
 ],['Before possible exposure: PrEP','After possible exposure: urgent PEP assessment','Established HIV: ART'],'PrE = pre/before. PE = post/after. ART = treat established infection.',[
 ['PrEP','Pre-exposure prophylaxis: HIV prevention medicine before possible exposure.','It is used by people without HIV as part of an appropriate prevention plan.'],
 ['PEP','Post-exposure prophylaxis: emergency prevention after possible HIV exposure.','Timing matters: immediate assessment, start as soon as possible and within 72 hours when indicated.'],
 ['Perinatal transmission','Transmission related to pregnancy, birth, or the period around birth.','Effective maternal treatment and infant management greatly reduce risk.']
 ],[
 q('What is PrEP used for?','Preventing HIV acquisition before potential exposure','PrEP is a prevention strategy for HIV-negative people in an appropriate care plan. It is different from treatment of established infection.',[['Only confirming an already reactive screen','PrEP is preventive medicine, not confirmation testing.'],['Replacing all ART in established HIV','Established infection needs an appropriate ART regimen.'],['Only emergency treatment begun after every exposure','That describes the PEP role.']]),
 q('What is the key timing principle for PEP?','Seek immediate assessment; start as soon as possible and within 72 hours when indicated','The opportunity for effective post-exposure prevention is time-sensitive. Do not wait for symptoms.',[['Wait until an antibody test becomes positive','That can miss the prevention window.'],['Begin only several months after exposure','That is too late for the usual PEP indication.'],['Start only after AIDS develops','PEP is prevention after possible exposure, not treatment of AIDS.']]),
 q('What reduces perinatal HIV transmission?','Effective maternal ART with appropriate pregnancy and infant management','Prevention is a coordinated strategy, including treatment, monitoring, infant care, and context-specific planning.',[['Only isolating the newborn socially','Social isolation does not replace prevention or medical care.'],['Avoiding all HIV testing in pregnancy','Testing supports diagnosis and prevention.'],['Assuming no symptoms means no transmission risk','Symptoms do not determine the need for care.']]),
 q('A worker sustains a potentially HIV-exposing needlestick. What is the appropriate next principle?','Follow the exposure protocol, report promptly, and obtain urgent assessment','PEP decisions are time-sensitive. Waiting for symptoms or test positivity can delay prevention.',[['Wait several weeks to see whether fever appears','Symptoms may be absent and the prevention window is short.'],['No action is needed if the patient looks healthy','Appearance does not establish infection or exposure risk.'],['Use PrEP retroactively without any assessment','Post-exposure care follows an appropriate PEP pathway.']],'Apply'),
 q('Why is a negative HIV result relevant before prescribing PrEP?','PrEP is designed for prevention in someone without established HIV','Possible infection must be assessed so established HIV receives appropriate treatment rather than an unsuitable prevention regimen.',[['PrEP is the standard complete treatment for every person with AIDS','Prevention and treatment regimens have different roles.'],['A negative result guarantees every future exposure is harmless','Prevention and follow-up remain important.'],['No testing is ever needed in prevention care','Testing is an important part of care.']],'Apply'),
 q('Which statement supports accurate and respectful HIV care?','HIV is not transmitted by ordinary casual contact, and treatment can protect health','Facts support safe care without stigma. Avoid blame and do not infer status or risk from identity.',[['Every patient with HIV must be excluded from ordinary shared spaces','Ordinary casual contact does not transmit HIV.'],['Only certain social identities can acquire HIV','Exposure routes, not identity alone, determine transmission possibility.'],['ART never changes prognosis','Effective treatment can greatly improve outcomes.']],'Apply')
 ],{ref:{label:'CDC · PEP',url:'https://www.cdc.gov/hiv/prevention/pep.html'}})
 ]
});
