import {COURSE,lesson,section,q} from './course.mjs';
COURSE.push({
 id:'seizures',title:'Seizures',label:'Brain activity & safety',week:'Week 3',icon:'zap',color:'#b46b19',source:'sources/seizures-slides.pdf',
 description:'Recognize seizure patterns, explain brain activity, and remember what safe care looks like.',
 lessons:[
 lesson('e1','What a seizure is & why it happens','2–5','A seizure is a temporary disturbance caused by abnormal excessive or synchronized brain activity.',[
 section('The electrical balance','Neurons communicate using electrical activity and chemical messengers called neurotransmitters. Normal activity depends on a balance between excitation, which encourages firing, and inhibition, which restrains firing. Altered membranes, ion distribution, neurotransmitters, or structural injury can disturb that balance. Symptoms depend on which brain networks are involved.'),
 section('A seizure is not always shaking','Abnormal activity can affect movement, sensation, awareness, behavior, or autonomic functions such as heart rate. Some seizures cause a stare or an unusual sensation without obvious convulsions. A seizure is an event; epilepsy is a disorder involving a persistent tendency to have seizures. One event does not automatically establish epilepsy.'),
 section('Provoked and unprovoked are about timing and context','An acute symptomatic, or provoked, seizure occurs in close association with an acute disturbance such as hypoglycemia, an electrolyte problem, infection, intoxication or withdrawal, or acute brain injury. An unprovoked seizure lacks that immediate acute trigger; it may still have a known underlying cause, such as a remote structural injury. The slide shortcut equating unprovoked with unknown cause is too narrow. Causes and management are assessed in context.')
 ],['Excitation/inhibition imbalance','Abnormal brain activity','Temporary functional change','Symptoms reflect the network involved'],'Event = seizure. Ongoing tendency = epilepsy. Shaking is only one possible sign.',[
 ['Neuron','A nerve cell that communicates through electrical and chemical signals.','A seizure reflects abnormal activity in brain networks rather than a universal muscle problem.'],
 ['Provoked seizure','A seizure closely associated with an acute disturbance or trigger.','Correcting that disturbance may be an important part of treatment.'],
 ['Epilepsy','A disorder involving a persistent predisposition to seizures.','A clinician applies diagnostic criteria; one seizure alone does not always establish it.']
 ],[
 q('Which statement best defines a seizure?','A temporary functional disturbance from abnormal brain electrical activity','The affected brain network determines the signs. Movement changes are common in some types but are not required in every seizure.',[['Every episode must involve whole-body shaking','Some seizures have sensory or awareness changes without convulsions.'],['It is always a permanent loss of all brain function','Seizures cause an abrupt temporary disturbance, although complications can be serious.'],['It is simply any emotional reaction','A seizure is a neurologic event.']]),
 q('What normally helps restrain excessive neuron firing?','Inhibitory activity','A healthy network balances excitation with inhibition. Reduced restraint can make abnormal firing more likely.',[['Unlimited excitation alone','Unopposed excitation can promote excessive activity.'],['Complete absence of all ion movement','Electrical signaling depends on controlled ion movement.'],['Only the size of the thyroid gland','That is not the neuronal excitation–inhibition balance.']]),
 q('Which is an example of an acute provoking disturbance?','Severe hypoglycemia','An acute metabolic disturbance can provoke a seizure. The event is evaluated with the timing and underlying cause.',[['A remote healed brain injury automatically means an acute trigger today','A remote structural cause is not necessarily an immediate provoking disturbance.'],['An ordinary pulse alone','A pulse value by itself is not an acute provoking cause.'],['Every unprovoked seizure has no possible known cause','A known underlying cause can exist without an acute trigger.']]),
 q('A person has one seizure during a severe electrolyte disturbance. What conclusion is appropriate?','The event may be acute symptomatic and does not automatically establish epilepsy','The immediate disturbance is relevant. A seizure event and the diagnosis of a persistent seizure disorder are different decisions.',[['One event always proves lifelong epilepsy','That ignores acute symptomatic causes.'],['No brain electrical activity is involved','A seizure still involves abnormal brain activity.'],['Only shaking can indicate a seizure','The manifestations vary by network and type.']],'Apply'),
 q('Why can two seizure types look very different?','Different brain networks control different functions','Motor, sensory, awareness, and autonomic networks can produce different outward signs when affected.',[['All neurons normally do exactly the same task','Networks have different functional roles.'],['A seizure cannot affect awareness','Awareness can be impaired in several types.'],['The symptoms depend only on the person’s height','Height does not define seizure manifestations.']],'Apply'),
 q('Which statement about an unprovoked seizure is accurate?','It may have a known underlying cause without an immediate acute trigger','Unprovoked is not synonymous with unknown cause. A remote structural problem can be relevant even when no acute metabolic disturbance is present.',[['The cause must always be completely unknown','This is too restrictive.'],['It must happen during acute hypoglycemia','That would suggest an acute provoking disturbance.'],['It can never be associated with epilepsy','Unprovoked seizures are central to many epilepsy diagnoses.']],'Apply')
 ]),
 lesson('e2','Focal seizures & awareness','6–9','Focal onset begins in networks on one side of the brain. Awareness can be preserved or impaired.',[
 section('Location and awareness are separate questions','Focal seizures arise in networks within one hemisphere. The slides distinguish those without impaired consciousness or awareness from those with impairment. A person with preserved awareness may describe an unusual smell, tingling, a rising abdominal sensation, or localized movement. Preserved awareness does not mean no seizure occurred.'),
 section('Aura and automatisms','An aura can be a subjective focal seizure symptom, often with awareness preserved. It may precede a larger seizure, but it is itself part of the seizure rather than merely an unrelated warning. Automatisms are repetitive, seemingly purposeless movements, such as lip-smacking or picking at clothing. They may occur in focal seizures with impaired awareness.'),
 section('Do not assume every focal event becomes generalized','Impaired awareness does not automatically mean activity has spread to both hemispheres. Some focal seizures remain focal; others evolve into a bilateral tonic-clonic seizure. Confusion after a focal seizure may occur during the postictal period. Classification terminology evolves, but the practical study questions remain: where did it begin, what functions were affected, and was consciousness or awareness impaired?')
 ],['One-hemisphere onset','Motor/sensory/autonomic changes','Awareness preserved or impaired','May remain focal or spread'],'Focal = where it starts. Awareness = what the person experiences.',[
 ['Aura','A subjective seizure symptom, often a focal event with preserved awareness.','An unusual smell or rising sensation can be part of a seizure.'],
 ['Automatism','A repetitive, seemingly purposeless movement during a seizure.','Examples include lip-smacking and repetitive hand movements.'],
 ['Postictal','The period after a seizure.','The person may need time to regain usual awareness, energy, or orientation.']
 ],[
 q('What defines focal onset?','The seizure begins in networks within one hemisphere','Onset location is the key classification feature. Awareness and later spread are additional features.',[['Every seizure begins in both hemispheres simultaneously','That describes generalized onset.'],['Only a complete loss of muscle tone','That describes a particular manifestation, not all focal onset.'],['Only unconsciousness determines the starting location','Consciousness does not by itself establish onset.']]),
 q('What is an aura in this context?','A subjective symptom that can itself be a focal seizure','It can precede more obvious activity but is not merely a non-seizure warning. The person may retain awareness during it.',[['Only confusion many days after a seizure','An aura concerns the seizure event itself.'],['Always whole-body rhythmic jerking','An aura can be sensory or autonomic.'],['A guarantee that no abnormal activity occurred','It may be a seizure manifestation.']]),
 q('Which is an example of an automatism?','Repeated lip-smacking during impaired awareness','Automatisms are repetitive, seemingly purposeless behaviors. They are useful observations in seizure characterization.',[['A measured high free T4','That is a laboratory result, not a movement.'],['A deliberate written description after recovery','That is not the repetitive ictal behavior described.'],['Every normal voluntary blink','Normal voluntary action does not establish an automatism.']]),
 q('A person reports an odd smell and remains able to describe it during the event. Which pattern is possible?','A focal seizure with preserved awareness','A seizure can cause a sensory change without loss of awareness. Full-body convulsions are not required.',[['A seizure is impossible because the person is aware','Focal seizures can preserve awareness.'],['All generalized tonic-clonic phases are proved','The scenario lacks that pattern.'],['The smell alone proves a specific diagnosis without evaluation','Symptoms still require assessment and context.']],'Apply'),
 q('A person has impaired awareness and repetitive hand movements. Must the seizure have spread to both hemispheres?','No, impaired awareness can occur in a seizure that remains focal','Consciousness or awareness can be affected by focal network activity. It should not be equated automatically with bilateral spread.',[['Yes, impaired awareness always proves generalized onset','Focal seizures can impair awareness.'],['No seizure type can impair awareness','Both focal and generalized seizure types can impair awareness; the change does not determine onset by itself.'],['Automatisms are impossible during focal activity','They can occur in focal impaired-awareness seizures.']],'Apply'),
 q('A seizure begins with focal symptoms and later becomes bilateral tonic-clonic. How should onset be understood?','It has focal onset with later bilateral spread','The initial site of onset remains important even when the later movements involve both sides.',[['The later movements erase all evidence of focal onset','Onset and evolution are both part of classification.'],['It must have begun as a typical absence seizure','The described focal onset does not establish absence.'],['It never involved brain activity','Both phases concern abnormal brain activity.']],'Apply')
 ]),
 lesson('e3','Absence, atonic & myoclonic patterns','10–14','Staring, loss of tone, and brief jerks describe different seizure manifestations.',[
 section('Absence: a brief interruption','A typical absence seizure causes a brief interruption of awareness, often with a blank stare and sometimes subtle eyelid or other movements. It usually lasts seconds with a rapid return to the previous activity and little or no postictal confusion. It is commonly recognized in childhood, but may persist beyond childhood. Not every stare or daydream is a seizure.'),
 section('Atonic: tone drops','An atonic seizure involves sudden loss of muscle tone. The head may drop, the knees may buckle, or the person may fall. Injury risk matters because the loss can be abrupt. Tone means the background muscle activity that supports posture; losing it is different from muscles stiffening or repeatedly jerking.'),
 section('Myoclonic: a brief jerk','Myoclonic seizures involve brief, shock-like muscle jerks, sometimes affecting both sides or selected body regions. Awareness may be preserved. Do not memorize that every generalized seizure necessarily causes complete unconsciousness. Generalized onset refers to bilaterally distributed networks from onset, while the clinical manifestations depend on the type. The slides emphasize these patterns as a way to distinguish appearances.')
 ],['Brief pause: absence','Sudden loss of tone: atonic','Brief jerk: myoclonic'],'Absent contact, atonic drop, myoclonic jerk.',[
 ['Absence seizure','A brief interruption of awareness, typically with rapid recovery.','A characteristic pattern is seconds of staring followed by resuming activity.'],
 ['Atonic seizure','A seizure involving sudden loss of muscle tone.','It can cause abrupt falls and injuries.'],
 ['Myoclonic seizure','A seizure involving brief, shock-like muscle jerks.','Brief jerks differ from a prolonged rhythmic clonic phase.']
 ],[
 q('Which pattern is most characteristic of a typical absence seizure?','A brief stare with rapid return to activity','Typical absence causes a short interruption, often without a prolonged postictal phase. Other causes of staring still require consideration.',[['Several hours of obligatory confusion after every event','That is not the typical absence pattern.'],['Only sustained muscle stiffness followed by long jerking','That is a tonic-clonic description.'],['Only a sudden loss of all muscle tone','That is an atonic description.']]),
 q('What is the defining manifestation of an atonic seizure?','Sudden loss of muscle tone','Tone loss can make the head drop or cause a fall. It differs from brief jerks and sustained stiffening.',[['Strong sustained stiffening','That is tonic activity.'],['Brief shock-like jerks only','That is myoclonic activity.'],['A requirement for a sensory aura in every case','An aura is not required to define atonic activity.']]),
 q('What describes myoclonic activity?','Brief, shock-like muscle jerks','The rapid jerks can involve one or more regions. They are not the same as prolonged alternating contraction and relaxation.',[['Permanent paralysis of all muscles','Myoclonus describes brief movement, not universal permanent paralysis.'],['Only a brief stare without any movement','That better describes typical absence.'],['Only loss of tone without a jerk','That is atonic activity.']]),
 q('A child repeatedly pauses for a few seconds, stares, and then immediately resumes a sentence. Which pattern deserves consideration?','Typical absence seizure','Brief interruption with immediate return is characteristic. Assessment is still needed to distinguish it from non-seizure behaviors.',[['Only generalized tonic-clonic seizure','The description lacks sustained stiffening and rhythmic convulsions.'],['Only an atonic drop attack','There is no described loss of postural tone.'],['Epilepsy is impossible without a fall','Seizures can occur without falls.']],'Apply'),
 q('Someone suddenly loses posture and falls without a prolonged stiffening phase. Which pattern fits the described tone change?','Atonic','Loss of tone is the distinguishing feature. Injury prevention is important because falls can be abrupt.',[['Tonic, because tonic means relaxed','Tonic means sustained contraction or stiffening.'],['Myoclonic, because all drops are necessarily jerks','A drop from tone loss differs from a brief contraction.'],['Absence, because awareness and tone are always identical','A brief awareness interruption and loss of muscle tone are distinct features.']],'Apply'),
 q('Why is the statement “every generalized seizure causes complete unconsciousness” too absolute?','Some generalized motor patterns can preserve awareness','Generalized describes onset networks. Awareness varies by seizure type, so classify the actual observed pattern.',[['Because generalized onset means only one hemisphere','That defines focal onset, not generalized.'],['Because generalized seizures are never neurologic events','They are neurologic events.'],['Because the type is determined only by pulse rate','Pulse rate alone does not classify a seizure.']],'Apply')
 ]),
 lesson('e4','Tonic-clonic & the recovery period','15','Tonic means stiffening; clonic means rhythmic contraction and relaxation.',[
 section('The two motor phases','A tonic-clonic seizure has a tonic phase of sustained muscle contraction and a clonic phase of repeated contraction and relaxation. Consciousness is lost during the event. Breathing may be impaired, and cyanosis (bluish discoloration) or incontinence may occur, but neither is necessary for every seizure. Tonic-clonic activity may be generalized from onset or develop from a focal seizure.'),
 section('Why recovery is not instantaneous','The postictal period follows the seizure. Confusion, sleepiness, headache, and muscle soreness may occur as brain and body recover. Recovery time varies; do not force the person to stand, drink, or immediately return to an activity. Assess breathing and safety, and watch whether responsiveness returns appropriately.'),
 section('Observation helps later care','Useful observations include what happened before onset, the first body region or behavior affected, duration, movement pattern, awareness, breathing changes, injury, and recovery. Time the event rather than estimating from memory. A failure to recover, repeated seizures, or breathing problems may require emergency escalation. Do not dismiss persistent impaired responsiveness as automatically normal postictal sleep.')
 ],['Tonic stiffening','Clonic rhythmic jerking','Postictal recovery'],'Tonic = tight. Clonic = cycles. Postictal = after.',[
 ['Tonic','Sustained muscle contraction or stiffening.','It is the first major motor phase in a typical tonic-clonic description.'],
 ['Clonic','Rhythmic repeated contraction and relaxation.','It produces the repeated jerking phase.'],
 ['Cyanosis','Bluish discoloration that may reflect inadequate oxygenation.','It can occur during impaired breathing and needs assessment.']
 ],[
 q('What does the tonic phase involve?','Sustained muscle stiffening','Tonic describes sustained contraction. The later clonic phase involves repeated contraction and relaxation.',[['Only relaxation with loss of tone','That is an atonic pattern.'],['Only rhythmic cycles of contraction and relaxation','That is clonic activity.'],['Only normal voluntary movement','The phase is seizure-related motor activity.']]),
 q('What does the clonic phase involve?','Rhythmic contraction and relaxation','Repeated cycles produce jerking. This differs from the sustained contraction of the tonic phase.',[['A single definition of low blood pressure','Clonic refers to muscle activity.'],['Only fixed continuous stiffening','That is tonic activity.'],['Only loss of background posture','That is atonic activity.']]),
 q('What does postictal mean?','The period after a seizure','Recovery may include confusion or sleepiness. Safety and breathing still need assessment.',[['The first sensation before every seizure','That is closer to an aura description.'],['The phase before brain activity begins','Postictal means after the seizure; an aura or pre-event experience belongs to a different part of the event.'],['A permanent diagnosis established by one movement','It describes a time period, not a complete diagnosis.']]),
 q('After a tonic-clonic seizure, a person is sleepy and confused. What is a safe interpretation?','This may be postictal recovery, but breathing and return of responsiveness must be assessed','Postictal symptoms are common, but persistent impairment or breathing difficulty should not be ignored.',[['All impaired breathing is always normal and needs no assessment','Breathing problems require attention.'],['Give water immediately while the person is unresponsive','Reduced consciousness can make swallowing unsafe, so oral food or water should wait until full alertness.'],['Force the person to walk to prove recovery','The person may be unsafe to stand.']],'Apply'),
 q('Which observation is particularly useful for characterizing the seizure?','The first sign, duration, movement pattern, and recovery','These features help establish onset and evolution and identify complications. Timing provides better information than an impression alone.',[['Only the room’s wall color','This does not characterize the event.'],['Only the person’s preferred food','This does not describe seizure activity.'],['No observations are useful after it stops','The course and recovery remain diagnostically important.']],'Apply'),
 q('Does urinary incontinence have to occur for a tonic-clonic seizure?','No, it may occur but is not required','A possible sign should not be treated as a mandatory feature. Classification considers the whole event.',[['Yes, its absence makes all seizure activity impossible','That rule is too absolute.'],['Yes, it is the only diagnostic feature','Many features contribute to diagnosis.'],['No, tonic-clonic seizures can never affect awareness','Consciousness is lost during tonic-clonic activity.']],'Apply')
 ]),
 lesson('e5','Diagnosis & longer-term control','16–17, 19','Electrical tests, structural tests, and metabolic tests answer different questions.',[
 section('Match the test to its question','An electroencephalogram (EEG) records brain electrical activity and can identify patterns supporting a seizure diagnosis. A normal routine EEG does not exclude epilepsy, because abnormal activity may not be captured in a short recording. Magnetic resonance imaging (MRI) or computed tomography (CT) evaluates structural causes such as injury or a mass. Blood tests can investigate acute metabolic disturbances, including glucose and electrolytes.'),
 section('Medicines are chosen for the seizure type','Antiseizure medicines reduce the likelihood of abnormal firing by acting on channels, signaling, or other targets. The slides give phenytoin and valproic acid as examples, not as a universal regimen. A drug suitable for one seizure type may not be appropriate for another. Long-term control and emergency rescue serve different purposes. Adherence, adverse effects, interactions, and follow-up matter.'),
 section('Other options and prognosis','Some people with seizures that persist despite appropriate medicines are evaluated for surgery or neurostimulation. Decisions depend on the seizure focus, syndrome, cause, and other factors. Prognosis varies; a percentage from a slide should not be used to predict one person’s outcome. Antiseizure medicine should not be stopped abruptly or independently just because the person feels better. Clinicians assess whether and how supervised withdrawal is suitable.')
 ],['Describe the event','EEG: electrical patterns','Imaging: structure','Labs: metabolic causes','Type-specific control'],'EEG = electrical. MRI/CT = structure. Labs = possible metabolic causes.',[
 ['EEG','Electroencephalogram: a recording of brain electrical activity.','It may support diagnosis, but a normal short recording does not exclude every seizure disorder.'],
 ['MRI / CT','Magnetic resonance imaging / computed tomography: structural imaging methods.','They help assess brain structure rather than directly recording neuronal firing.'],
 ['Antiseizure medicine','A medicine intended to reduce seizures through effects on neuronal activity.','Treatment choice depends on the seizure type and patient context.']
 ],[
 q('What does an EEG primarily assess?','Brain electrical activity','An EEG records electrical patterns. Structural imaging and blood tests answer different questions.',[['The exact iron content of meals','That is not the purpose of EEG.'],['Thyroid nodule histology','That requires tissue assessment.'],['Only the size of brain structures','Structural imaging evaluates that more directly.']]),
 q('What can MRI or CT help identify?','Structural brain causes','Imaging may show lesions or injury relevant to a seizure. It does not replace event description or electrical assessment.',[['A complete real-time replacement for every EEG recording','Imaging and EEG are different types of tests.'],['Only TSH secretion','These are not thyroid-function blood tests.'],['Always the exact seizure frequency without history','Frequency requires event history and monitoring.']]),
 q('Why are glucose and electrolyte tests sometimes obtained?','To investigate possible acute metabolic provoking factors','Metabolic disturbances can produce acute symptomatic seizures. Identifying the disturbance can guide treatment.',[['They identify every epileptic syndrome without any other evaluation','Metabolic tests investigate acute triggers; they do not independently classify every seizure disorder.'],['They replace every neurologic assessment','They are one part of an evaluation.'],['No metabolic disturbance can affect neurons','Controlled ion and fuel conditions are important to brain function.']]),
 q('A normal routine EEG is recorded between events. What should be understood?','It does not by itself exclude epilepsy','A short test may not capture abnormal activity. Clinicians interpret it alongside history and other evidence.',[['Epilepsy is automatically impossible','A normal routine recording does not rule it out.'],['Every observed event must therefore be intentional','This conclusion is unsupported.'],['Structural imaging is never useful afterward','Additional evaluation may still be appropriate.']],'Apply'),
 q('Why should antiseizure medicine selection depend on seizure type?','Different types respond differently to specific treatments','Medicine targets and clinical evidence differ. An example drug on a slide is not a universal prescription.',[['Every drug is interchangeable for every seizure type','The seizure type and patient context affect which medicines work and which may be unsuitable.'],['Only the tablet color determines response','Pharmacologic action and seizure type matter.'],['Long-term and rescue treatments always have identical roles','Their purposes and usage differ.']],'Apply'),
 q('A person has been seizure-free and wants to stop the medicine abruptly. Which principle fits?','Any withdrawal should be assessed and supervised by a clinician','Feeling well may reflect successful treatment. Abrupt independent stopping can increase seizure risk.',[['Stopping suddenly is always safe once one day has passed','This ignores relapse and withdrawal risks.'],['Medication adherence is unrelated to seizure control','Consistent prescribed treatment can help maintain seizure control; missed treatment may contribute to recurrence.'],['Every person needs exactly the same lifelong regimen','Duration and regimen are individualized.']],'Apply')
 ]),
 lesson('e6','Safe first aid, status & SUDEP','17–19','Time the event, protect the person, assess breathing, and recognize when urgent help is needed.',[
 section('What to do and avoid','Stay with the person, clear nearby hazards, cushion the head, and gently turn them onto their side when safe. Time the seizure. Do not restrain the movements, put objects in the mouth, or give food or drinks before full alertness. Afterward, check breathing and help the person recover safely. In a clinical setting, use the appropriate emergency protocol and any prescribed rescue plan.'),
 section('The five-minute emergency principle','A continuous convulsive tonic-clonic seizure around five minutes, or repeated seizures without recovery, requires urgent emergency action. Other triggers for urgent help include breathing difficulty, injury, a first seizure, pregnancy, or an event in water. The older thirty-minute status statement in the slides must not be used as a waiting rule. Prolonged abnormal activity can threaten breathing and injure the brain; status management includes urgent support, seizure-stopping medicine such as a benzodiazepine in a clinical protocol, and evaluation of the cause.'),
 section('Keep rescue and prevention distinct','Lorazepam is one example of a benzodiazepine used in monitored acute care; it is not a universal unsupervised home prescription. Long-term treatment aims to reduce future events. Sudden unexpected death in epilepsy (SUDEP) is a serious complication, and ongoing seizure control and individualized safety planning matter. It is not an inevitable outcome. Learn the recognition and safety principles without guessing a person’s risk from a study quiz.')
 ],['Recognize & time','Protect from injury','Support safe recovery','Escalate if prolonged or unsafe'],'Time it. Protect. Side when safe. Nothing in the mouth. Do not wait thirty minutes.',[
 ['Status epilepticus','Prolonged seizure activity or repeated seizures without adequate recovery.','For convulsive tonic-clonic activity, five minutes is an important emergency-action threshold.'],
 ['Benzodiazepine','A medicine class used in acute seizure treatment under an appropriate protocol.','Emergency rescue has a different role from routine long-term seizure prevention.'],
 ['SUDEP','Sudden unexpected death in epilepsy.','It is a serious possible complication, not a certain outcome for every person with epilepsy.']
 ],[
 q('What should be put in a person’s mouth during a convulsive seizure?','Nothing','Objects can injure the teeth or jaw and compromise safety. A person should not be restrained or given food or drink before alertness returns.',[['A spoon to prevent swallowing the tongue','A spoon can cause injury; this is unsafe advice.'],['Water to stop the movements','This can cause choking.'],['A finger to force the jaw open','This risks injury to both people.']]),
 q('What is the emergency principle for a continuous tonic-clonic seizure?','Take urgent emergency action around five minutes','Continuous convulsive activity around this duration is time-critical. Repeated seizures without recovery are also concerning.',[['Wait until thirty minutes before seeking help','The older slide statement is not a safe waiting rule.'],['Always wait several hours for spontaneous recovery','This delays urgent care.'],['Ignore the duration if the person is young','Age does not remove prolonged-seizure concern.']]),
 q('What does SUDEP stand for?','Sudden unexpected death in epilepsy','It is a serious complication discussed in epilepsy care. It is not a prediction that every patient will experience it.',[['Sudden universal deficiency of erythrocyte protein','This is not the abbreviation.'],['A standard test of thyroid function','SUDEP is not a thyroid test.'],['A guarantee of death after every seizure','It does not mean an inevitable outcome.']]),
 q('A tonic-clonic seizure continues for six minutes. What should happen?','Activate urgent emergency care and follow the applicable rescue protocol','This has crossed the important convulsive emergency threshold. Protection, airway assessment, and timely treatment are necessary.',[['Continue waiting until the older thirty-minute interval','Prolonged convulsive activity is time-critical; waiting for the older thirty-minute interval can delay emergency treatment.'],['Give oral food while the person convulses','Reduced consciousness can make swallowing unsafe, so oral food or water should wait until full alertness.'],['Hold the limbs tightly until movement stops','Restraint can cause injury.']],'Apply'),
 q('Another seizure begins before the person regains consciousness. Which interpretation is appropriate?','Repeated seizures without recovery are an emergency concern','Adequate recovery between events matters. Repeated activity can threaten breathing and requires urgent evaluation.',[['It is automatically ordinary recovery','The lack of recovery is a concerning feature.'],['Only the total number of years with epilepsy matters','The immediate pattern matters.'],['No timing or breathing assessment is needed','Timing identifies prolonged activity, while breathing assessment identifies an immediate safety concern.']],'Apply'),
 q('After a seizure, when is it appropriate to offer water?','After the person is fully alert and can swallow safely','Reduced awareness can make swallowing unsafe. Support recovery and assess breathing first.',[['During the active convulsions','This creates choking risk.'],['While the person remains unresponsive','Swallowing is not safely assured.'],['Whenever the mouth can be forced open','Forcing the mouth is unsafe.']],'Apply')
 ],{update:'Clinical update: do not wait thirty minutes. Convulsive tonic-clonic activity around five minutes, or repeated seizures without recovery, requires urgent emergency action.',ref:{label:'CDC · Seizure first aid',url:'https://www.cdc.gov/epilepsy/first-aid-for-seizures/index.html'}})
 ]
});
