import {COURSE,lesson,section,q} from './course.mjs';
COURSE.push({
 id:'thyroid',title:'Thyroid disorders',label:'Hormones & metabolism',week:'Week 2',icon:'sliders',color:'#6555b3',source:'sources/thyroid-slides.pdf',
 description:'Make sense of thyroid feedback, opposite symptom patterns, and the reason behind treatment.',
 lessons:[
 lesson('t1','The hormone feedback loop','2–4','TSH is a signal to the thyroid; T3 and T4 are hormones produced by the thyroid.',[
 section('Follow the messages','The hypothalamus releases thyrotropin-releasing hormone (TRH). TRH signals the pituitary gland to release thyroid-stimulating hormone (TSH). TSH stimulates the thyroid to make triiodothyronine (T3) and thyroxine (T4). These hormones help regulate energy use, heat production, growth, and many organ functions. Most hormone in blood is protein-bound; free T4 is the unbound fraction available to tissues.'),
 section('Negative feedback is a thermostat','When enough T3 and T4 are present, they reduce the upstream signal. When thyroid hormone is too low, the pituitary usually increases TSH to ask for more. In primary thyroid disease, the gland itself is the problem: overt primary hypothyroidism usually means high TSH with low free T4; overt primary hyperthyroidism usually means low TSH with high free T4 and/or T3.'),
 section('Know the important exception','If the pituitary or hypothalamus is the problem, the expected rise in TSH may not occur. Central hypothyroidism can show low free T4 with low or inappropriately normal TSH. Therefore, the shortcut of opposite TSH and T4 directions applies most cleanly to primary gland disease. Symptoms, history, free hormone results, and context complete the interpretation.')
 ],['Hypothalamus: TRH','Pituitary: TSH','Thyroid: T3 & T4','Feedback reduces upstream signals'],'TSH is the request. T3/T4 are the thyroid’s response.',[
 ['TSH','Thyroid-stimulating hormone: a pituitary signal that stimulates the thyroid.','High TSH often means the pituitary is asking an underactive thyroid to work harder.'],
 ['T3 / T4','Triiodothyronine / thyroxine: hormones made by the thyroid.','They support metabolic activity and feed back on the hypothalamus and pituitary.'],
 ['Negative feedback','A response that reduces the original stimulating signal when enough output is present.','Higher thyroid hormone usually suppresses TSH in an intact axis.']
 ],[
 q('Where is TSH produced?','The pituitary gland','TSH is an upstream signal, not a thyroid-produced hormone. The thyroid responds by producing T3 and T4.',[['The thyroid gland','The thyroid produces T3 and T4, not TSH.'],['Only the adrenal cortex','The adrenal cortex produces other hormones.'],['The parathyroid glands','These mainly regulate calcium through parathyroid hormone.']]),
 q('What normally happens to TSH when T3 and T4 rise sufficiently?','TSH decreases through negative feedback','The output hormones signal that further stimulation is less necessary. This feedback helps maintain balance.',[['TSH must rise indefinitely','That would not be normal negative feedback.'],['The pituitary instantly becomes the thyroid','These remain separate organs.'],['TSH becomes irrelevant in every situation','It remains an important signal and test.']]),
 q('Which pattern fits overt primary hypothyroidism?','High TSH and low free T4','A failing thyroid supplies too little hormone, so an intact pituitary increases its request. The word primary identifies the thyroid gland as the problem.',[['Low TSH and high free T4','That usually fits primary hyperthyroidism.'],['High TSH and high free T4 in every case','That does not fit the usual overt primary hypothyroid pattern.'],['Normal free T4 is required for overt disease','Overt primary hypothyroidism has low free T4.']]),
 q('Free T4 is high and TSH is suppressed. Which pattern is most consistent?','Primary hyperthyroidism','Increased thyroid output feeds back to suppress the pituitary signal. T3 results and the clinical assessment help clarify the cause.',[['Overt primary hypothyroidism','That usually has high TSH and low free T4.'],['Intrinsic-factor deficiency','That does not define this thyroid feedback pattern.'],['The thyroid cannot be making hormone','The elevated free T4 indicates excess circulating hormone.']],'Apply'),
 q('Why might a low free T4 with a non-elevated TSH suggest central hypothyroidism?','The upstream gland may fail to provide an appropriate stimulating signal','An intact pituitary should usually raise TSH when thyroid hormone is low. An inadequate rise suggests an upstream problem in the proper context.',[['A normal TSH excludes every thyroid disorder','Central disease may have inappropriately normal TSH.'],['Every hypothyroid case must have suppressed free T4 and very high TSH','That rule is too absolute for central disease.'],['TSH is made only after thyroid removal','It is normally produced by the pituitary.']],'Apply'),
 q('Why distinguish free T4 from protein-bound hormone?','Free T4 reflects the unbound hormone fraction','Binding-protein changes can affect total hormone levels. Free hormone and TSH provide useful complementary information.',[['Free T4 is a white blood-cell count','It is a thyroid hormone measurement.'],['Protein binding makes all T4 permanently inactive and unmeasurable','Bound hormone can act as a circulating reservoir; free levels remain clinically useful.'],['Free T4 is identical to TSH','They are different hormones from different organs.']],'Apply')
 ]),
 lesson('t2','Hypothyroidism: metabolism slows','6–11','Too little thyroid hormone slows many processes; the signs follow that mechanism.',[
 section('Why the symptoms cluster','Reduced metabolic activity can produce fatigue, cold intolerance, weight gain, constipation, slowed heart rate, and slower thinking. Dry skin and coarse hair may appear. Symptoms vary and overlap many other conditions, so a symptom list is not a diagnosis. Myxedema refers to tissue changes that can produce non-pitting swelling because water is held within accumulated substances in the tissue.'),
 section('Different paths to the same deficiency','Hashimoto thyroiditis is an autoimmune process that can damage the thyroid. Thyroid removal, certain treatments for hyperthyroidism, some medications, and iodine-related problems can also produce low hormone. Primary disease originates in the gland; central disease originates in the upstream control system. Connect the cause with the TSH/free T4 interpretation rather than memorizing one result for every case.'),
 section('Replace the missing hormone','Levothyroxine is synthetic T4 used for replacement. Improvement and dose adjustment are assessed with symptoms and appropriate lab follow-up; it is not an immediate stimulant. Iron and calcium can reduce its absorption when taken together, so dosing instructions and interactions matter. Patients with cardiac disease require particular care with treatment adjustment. Severe deterioration with altered consciousness, hypothermia, and respiratory compromise can signal a myxedema emergency.')
 ],['Low thyroid hormone','Lower metabolic activity','Cold, tired, slow pattern','Replacement & reassessment'],'Hypo: think slower and colder, then confirm with tests.',[
 ['Hashimoto thyroiditis','An autoimmune thyroid disorder that commonly leads to hypothyroidism.','Damage reduces the gland’s ability to supply hormone.'],
 ['Myxedema','Tissue changes associated with hypothyroidism, including non-pitting swelling.','It is not simply ordinary dependent edema from fluid overload.'],
 ['Levothyroxine','Synthetic thyroxine (T4) used for thyroid hormone replacement.','Its role is to replace a deficiency; absorption and follow-up matter.']
 ],[
 q('Which cluster is more typical of hypothyroidism?','Cold intolerance, constipation, fatigue, and slowed pulse','These findings fit reduced metabolic activity. They must still be interpreted with thyroid tests and context.',[['Heat intolerance, tremor, and rapid pulse','This pattern more strongly fits hormone excess.'],['Weight loss despite increased appetite and frequent stools','That is more characteristic of hyperthyroidism.'],['High fever and extreme agitation as the usual mild pattern','That is not the usual mild hypothyroid pattern.']]),
 q('How can Hashimoto thyroiditis lead to hypothyroidism?','Autoimmune damage reduces thyroid function','The gland loses the ability to provide adequate hormone. This differs from Graves antibodies that stimulate hormone production.',[['Antibodies always stimulate maximal thyroid output','That better describes the Graves mechanism.'],['The pituitary converts into thyroid tissue','That is not the mechanism.'],['Only an acute allergic airway response occurs','Hashimoto is not anaphylaxis.']]),
 q('What is levothyroxine intended to do?','Replace deficient thyroid hormone','It is synthetic T4. Dosing aims to restore appropriate hormone function, with monitoring rather than relying on symptoms alone.',[['Destroy every thyroid cell','That is not replacement therapy.'],['Act only as a beta-blocker','It is a hormone, not a beta-receptor blocker.'],['Stop all pituitary secretion permanently','Replacement supports feedback but does not mean universal permanent pituitary shutdown.']]),
 q('Fatigue, weight gain, constipation, high TSH, and low free T4 occur together. What best explains them?','Overt primary hypothyroidism','The symptom direction is slow metabolism, and the gland-level feedback pattern is high request with low output.',[['Graves hyperthyroidism','That usually has excess hormone and suppressed TSH.'],['Normal thyroid function proved by high TSH','A high TSH with low free T4 is not a normal pattern.'],['Thyroid storm','The pattern describes low rather than excessive hormone activity.']],'Apply'),
 q('Why should iron or calcium use be reviewed in someone taking levothyroxine?','They can interfere with absorption when taken together','Reduced absorption may affect replacement effectiveness. Patients follow clinician or pharmacist instructions about timing.',[['They guarantee improved absorption when swallowed at the same time','They can instead reduce absorption.'],['They turn T4 into HIV RNA','That is not a drug interaction.'],['They make all lab follow-up unnecessary','Monitoring remains important.']],'Apply'),
 q('What does non-pitting swelling in hypothyroidism refer to?','Myxedematous tissue involvement','Substances accumulating in tissue can bind water and produce firm swelling. This explains a specific hypothyroid manifestation.',[['The defining sign of every goiter','A goiter is thyroid enlargement, not this tissue swelling.'],['A direct measurement of MCV','MCV describes RBC size.'],['Proof that thyroid hormone is always high','Myxedema is associated with deficient thyroid function.']],'Apply')
 ],{ref:{label:'NIDDK · Hypothyroidism',url:'https://www.niddk.nih.gov/health-information/endocrine-diseases/hypothyroidism'}}),
 lesson('t3','Goiter & congenital hypothyroidism','5, 12–13','An enlarged thyroid tells you about size, not automatically about hormone output.',[
 section('Why a thyroid can enlarge','Goiter means enlargement of the thyroid gland. It can occur with high, low, or normal thyroid hormone function. In iodine deficiency, the thyroid lacks a building material for T3/T4; increased TSH stimulation can make it grow while hormone production remains inadequate. Graves disease can enlarge the gland through antibody stimulation while hormone output is high.'),
 section('Congenital means present from birth','Congenital hypothyroidism can result from an absent or abnormally developed thyroid, impaired hormone synthesis, or central-control problems. Thyroid hormone is essential for early brain development and growth. A baby may initially appear well, partly because of maternal hormone exposure and the timing of signs. A normal-looking newborn therefore cannot substitute for screening.'),
 section('Screen early and treat promptly','Newborn screening uses blood testing, commonly from a heel-prick sample, to identify abnormal TSH and/or T4 patterns according to the screening program. Prompt confirmatory assessment and hormone replacement protect development. The slides use an older term for untreated developmental effects and a six-week treatment statement; do not treat six weeks as a safe waiting period. The practical principle is early detection and prompt treatment. Possible later clues include poor feeding, prolonged jaundice, low activity, constipation, and impaired growth.')
 ],['Possible gland/synthesis problem','Low hormone in early life','Risk to growth & brain development','Screen & treat promptly'],'Goiter = size. Thyroid tests = function. Newborn screening = early detection.',[
 ['Goiter','An enlarged thyroid gland.','It can occur with underactivity, overactivity, or normal hormone function.'],
 ['Congenital','Present from birth.','A condition can be present before symptoms are obvious.'],
 ['Newborn screening','Early testing designed to detect important disorders before clear symptoms.','For congenital hypothyroidism, early identification supports prompt hormone replacement.']
 ],[
 q('What does goiter mean?','Enlargement of the thyroid gland','Goiter describes size. Hormone tests are needed to assess whether function is low, high, or normal.',[['Always excess thyroid hormone','Goiter can occur with several functional states.'],['Always low thyroid hormone','An enlarged gland is not necessarily underactive.'],['A low pituitary TSH in every case','TSH depends on the cause and hormone output.']]),
 q('Why can iodine deficiency cause a goiter?','Low hormone production increases stimulating drive to the thyroid','Iodine is needed for hormone synthesis. Compensatory TSH stimulation can enlarge the gland even while output remains inadequate.',[['Iodine has no role in T3/T4 synthesis','It is a building component of thyroid hormones.'],['The gland must be overproducing T4 in every iodine-deficient case','Missing iodine can impair hormone synthesis even while TSH stimulation makes the gland enlarge.'],['Every goiter is cancer','Goiters have several possible causes.']]),
 q('Why is newborn screening important for congenital hypothyroidism?','The baby may appear normal before developmental harm becomes obvious','Waiting for symptoms can delay treatment during a critical developmental period. Screening helps identify the problem early.',[['A normal-looking infant can never have low thyroid hormone','Early appearance can be misleading.'],['Screening replaces all treatment','Testing identifies a problem; treatment still follows.'],['Thyroid hormone is irrelevant in early life','It is important for brain development and growth.']]),
 q('Two patients have goiters; one has high free T4 and one has low free T4. Is that possible?','Yes, goiter can occur with different hormone states','An enlarged gland is a structural finding. Its function depends on the underlying cause.',[['No, all goiters must have identical hormone values','Size does not determine one hormone pattern.'],['Only if both blood tests are necessarily wrong','Different causes can produce different results.'],['No, goiter means the thyroid is absent','Goiter means enlargement, not absence.']],'Apply'),
 q('Why should treatment not be delayed until a screened infant develops clear symptoms?','Thyroid hormone supports time-sensitive brain development','Early replacement reduces preventable developmental harm. The goal is prompt care following an abnormal screen and confirmatory assessment.',[['Symptoms must always precede treatment','Screening exists to detect problems early.'],['The first six weeks are automatically safe without hormone','An older slide statement should not be used as a waiting rule.'],['Thyroid hormone is only important after puberty','It is important from early life.']],'Apply'),
 q('What does an abnormal newborn thyroid screen usually require next?','Prompt confirmatory assessment and treatment planning','A screening result triggers timely evaluation. It should not be ignored solely because the infant looks healthy.',[['No action until adulthood','That delays needed care.'],['Automatic radioactive iodine therapy for every infant','Congenital hypothyroidism generally needs replacement, not gland ablation.'],['Only observation of eye prominence','Appearance alone does not confirm hormone function.']],'Apply')
 ]),
 lesson('t4','Hyperthyroidism & Graves disease','14–17','Excess hormone speeds metabolism. Graves disease stimulates the thyroid through antibodies.',[
 section('Why the body feels sped up','Excess thyroid hormone increases metabolic activity and oxygen demand and amplifies sympathetic effects. Heat intolerance, sweating, tremor, palpitations, rapid pulse, frequent stools, nervousness, and weight loss despite appetite can occur. Older adults may have less typical presentations. Overt primary hyperthyroidism usually suppresses TSH while free T4 and/or T3 are elevated.'),
 section('Graves is stimulation, not destruction','In Graves disease, antibodies stimulate the TSH receptor, encouraging the thyroid to produce excess hormone. Goiter and thyroid eye disease can occur. Exophthalmos means eye protrusion, but not everyone with Graves has it and it is not required for all hyperthyroidism. Dermopathy describes characteristic skin changes in some patients. Contrast Hashimoto: autoimmune damage commonly reduces hormone supply.'),
 section('Hormone excess and overproduction are different ideas','Hyperthyroidism specifically refers to increased synthesis and secretion by the gland. Thyrotoxicosis is the broader state caused by excessive thyroid hormone action, including excess medication or release of stored hormone during thyroiditis. Autonomous nodules can also overproduce hormone. An adenoma is generally a benign tumor; the slide parenthesis equating adenoma with cancer is too absolute. The cause influences which treatment is appropriate.')
 ],['TSH-receptor stimulation','Increased thyroid output','More metabolic activity','Heat, tremor & rapid pulse'],'Graves stimulates. Hashimoto damages. Confirm with the hormone pattern.',[
 ['Graves disease','Autoimmune stimulation of thyroid hormone production through TSH-receptor antibodies.','It is a common cause of hyperthyroidism.'],
 ['Thyrotoxicosis','The state of excessive thyroid hormone action, regardless of the source.','It includes but is broader than gland overproduction.'],
 ['Exophthalmos','Protrusion of the eyes, which may occur with thyroid eye disease.','It is a possible Graves clue, not a requirement for every case.']
 ],[
 q('Which symptom cluster fits hyperthyroidism better?','Heat intolerance, tremor, weight loss, and rapid pulse','These changes fit increased metabolism and amplified sympathetic effects. They contrast with the slowed pattern of hypothyroidism.',[['Cold intolerance, constipation, and slowed pulse','That cluster favors low hormone.'],['Only non-pitting swelling with low free T4','That favors hypothyroid tissue involvement.'],['Only impaired RBC production','That is not the thyroid-excess symptom cluster.']]),
 q('What do Graves-related antibodies do?','Stimulate the TSH receptor on the thyroid','The gland receives persistent stimulating signals and can overproduce hormone despite suppressed pituitary TSH.',[['Always destroy the gland without any stimulation','That better fits the general Hashimoto damage concept.'],['Replace all T3 and T4 with pituitary TSH','These are different hormones.'],['Only remove iodine from all tissues','That is not the antibody mechanism.']]),
 q('Which statement about exophthalmos is accurate?','It can occur in Graves disease but is not universal','Eye involvement is a useful clue when present. Its absence does not rule out Graves or other causes of hyperthyroidism.',[['It must occur in every case of excess thyroid hormone','Not every patient has thyroid eye disease.'],['It proves low thyroid hormone in every case','It is classically associated with Graves-related eye disease.'],['It is the same as thyroid enlargement','Eye protrusion and goiter are different findings.']]),
 q('Why can someone with hyperthyroidism lose weight despite eating more?','Increased metabolic activity uses more energy','Higher hormone activity increases fuel use. Increased appetite may not fully compensate for that expenditure.',[['Thyroid excess always stops all metabolism','It increases metabolic activity.'],['Food contains no energy during Graves disease','The change concerns energy expenditure.'],['The pituitary is producing hemoglobin','That is unrelated to the weight mechanism.']],'Apply'),
 q('Which comparison correctly separates Graves from Hashimoto?','Graves commonly stimulates excess output; Hashimoto commonly reduces function through damage','Both are autoimmune thyroid disorders, but the dominant mechanisms and usual hormone directions differ.',[['Both must always produce high free T4 forever','Hashimoto commonly progresses to low function.'],['Graves is a congenital lack of all thyroid tissue','That is not its antibody-stimulation mechanism.'],['Hashimoto is caused only by taking too much levothyroxine','It is an autoimmune disease.']],'Apply'),
 q('Excess levothyroxine causes symptoms of excess hormone. Which broader term fits?','Thyrotoxicosis','Excess hormone action can result from an external hormone source. The gland does not have to be overproducing it.',[['Primary gland overproduction is automatically proved','Medication-related excess can occur without increased synthesis by the gland.'],['Congenital hypothyroidism is proved','The described state is hormone excess.'],['Myxedema from deficient hormone','That describes a low-hormone state.']],'Apply')
 ]),
 lesson('t5','Tests & treatments: match the purpose','3, 11, 18','A test of function, a test of cause, and a treatment of symptoms serve different jobs.',[
 section('What each test contributes','TSH and free T4 help assess function; T3 may clarify some hormone-excess patterns. Antibody tests can support autoimmune causes. A radioactive iodine uptake test evaluates how the gland takes up iodine and can help distinguish causes of thyrotoxicosis. Imaging shows structure or activity patterns. Fine-needle biopsy samples a nodule to assess its cellular features; it is not the main test for measuring hormone output.'),
 section('Separate symptom control from synthesis control','Beta-blockers help control symptoms such as tachycardia and tremor; they do not ordinarily eliminate the underlying overproduction. Antithyroid medicines such as methimazole and propylthiouracil (PTU) reduce new hormone synthesis. Iodide preparations have selected uses in controlling release and preparing for surgery or treating crisis; they are not a universal self-treatment.'),
 section('Other options address the gland itself','Radioactive iodine therapy reduces active thyroid tissue over time; thyroid surgery removes tissue. Either can lead to hypothyroidism requiring replacement. Radioactive iodine treatment is avoided in pregnancy and breastfeeding. The choice depends on cause, pregnancy status, comorbidities, and patient-specific factors. Keep treatment categories separate: replace missing hormone, control excess synthesis, reduce symptoms, or reduce functioning tissue.')
 ],['Establish hormone pattern','Clarify the cause','Choose a treatment target','Monitor response'],'Function tests ask how much. Cause tests ask why. Treatment asks what to change.',[
 ['PTU','Propylthiouracil: an antithyroid medicine that reduces hormone synthesis.','It also reduces peripheral T4-to-T3 conversion and has selected clinical uses.'],
 ['Beta-blocker','A medicine that blocks beta-adrenergic effects such as a rapid pulse.','Symptom relief is different from stopping the thyroid’s hormone synthesis.'],
 ['Fine-needle biopsy','Sampling cells from a thyroid nodule with a thin needle.','It evaluates cellular features rather than directly measuring circulating hormone levels.']
 ],[
 q('Which tests most directly help assess thyroid hormone function?','TSH and free T4','These help interpret the upstream request and available hormone output. Other tests help establish cause or evaluate structure.',[['A nodule biopsy alone','A biopsy samples cells; it does not directly measure hormone function.'],['Only a neck photograph','Appearance does not establish hormone levels.'],['Only serum ferritin','Ferritin relates to iron stores.']]),
 q('Why may a beta-blocker be used in hyperthyroidism?','To reduce symptoms such as rapid pulse and tremor','It targets adrenergic effects. It does not usually remove the gland or fully stop its new hormone synthesis.',[['To replace deficient T4 in every case','That is the role of levothyroxine in deficiency.'],['To destroy thyroid tissue with radiation','That is radioactive iodine therapy.'],['To establish a thyroid nodule’s cell diagnosis','That is a diagnostic sampling task.']]),
 q('What do methimazole and PTU primarily reduce?','New thyroid hormone synthesis','These antithyroid medicines target production. They differ from replacement hormones and symptom-control drugs.',[['Only the number of CD4 cells','That is not their thyroid-treatment target.'],['All pituitary tissue permanently','They do not universally destroy the pituitary.'],['The need for any follow-up tests','Follow-up remains necessary.']]),
 q('After radioactive iodine treatment for hyperthyroidism, why might levothyroxine later be needed?','Reduced functioning tissue can cause hypothyroidism','The treatment lowers hormone-producing capacity. Replacement may be necessary if the remaining output becomes inadequate.',[['Radioactive iodine always increases T4 forever','Its intended effect is to reduce active thyroid tissue.'],['Levothyroxine is only a seizure rescue drug','It is thyroid hormone replacement.'],['No treatment can ever change thyroid function','Treatments can substantially change output.']],'Apply'),
 q('Which purpose best matches fine-needle thyroid biopsy?','Evaluating the cellular nature of a thyroid nodule','Sampling helps assess features such as malignancy risk. Hormone function still needs appropriate blood testing.',[['Calculating cardiac output','That uses circulation measurements.'],['Replacing the missing thyroid hormone','A biopsy is not replacement therapy.'],['Directly measuring free T4 concentration','That is a blood-test measurement.']],'Apply'),
 q('Why is radioactive iodine avoided in pregnancy?','It can harm the developing fetal thyroid','Treatment choice considers fetal exposure. Pregnancy and breastfeeding require appropriate alternatives and specialist assessment.',[['It is always the preferred treatment for every pregnant patient','It is contraindicated in this setting.'],['It contains no biologically active radiation','Its therapeutic action depends on radiation.'],['The fetal thyroid never uses iodine','Iodine is relevant to fetal thyroid development and function.']],'Apply')
 ],{ref:{label:'NIDDK · Hyperthyroidism',url:'https://www.niddk.nih.gov/health-information/endocrine-diseases/hyperthyroidism'}}),
 lesson('t6','Thyroid storm & comparing emergencies','19–20','Thyroid storm is severe clinical decompensation from hormone excess, not simply a high lab number.',[
 section('Recognize the whole emergency','Thyroid storm can occur when thyrotoxicosis becomes severely destabilizing. Marked fever, extreme tachycardia or arrhythmia, agitation, delirium, gastrointestinal symptoms, and heart failure can occur. Infection, surgery, trauma, and other stressors may trigger it. The diagnosis is clinical: an isolated high T4 does not, by itself, establish storm or its severity.'),
 section('Why treatment has several targets','Emergency care supports airway, breathing, circulation, temperature, and metabolic needs while treating the trigger. Beta-blockade addresses selected adrenergic effects; antithyroid therapy reduces synthesis; iodide in a properly sequenced protocol reduces release; glucocorticoids have additional roles. The clinician chooses the regimen and sequence. Different targets are needed because symptoms, production, release, and systemic failure are not one identical problem.'),
 section('Contrast the opposite emergency','A myxedema emergency comes from severe deficient thyroid function and may involve hypothermia, reduced responsiveness, slow ventilation, and circulatory compromise. Storm is generally the hot, fast, excess-hormone pattern; myxedema emergency is generally the cold, slow, deficient-hormone pattern. These are recognition patterns, not home diagnostic tools. Both require urgent clinical care. Do not wait for a particular hormone number before responding to severe deterioration.')
 ],['Underlying thyrotoxicosis','Triggering stressor','Severe systemic decompensation','Urgent multi-target treatment'],'Storm: hot and fast with systemic failure. Myxedema emergency: cold and slow.',[
 ['Thyroid storm','Life-threatening clinical deterioration due to severe thyrotoxicosis.','Clinical features and organ dysfunction matter more than a T4 number alone.'],
 ['CNS','Central nervous system: the brain and spinal cord.','Agitation, delirium, or reduced responsiveness show that a thyroid crisis can affect the nervous system.'],
 ['Myxedema emergency','Severe decompensated hypothyroidism, often called myxedema coma.','A person need not be literally comatose for the condition to be serious.']
 ],[
 q('Which cluster raises concern for thyroid storm?','High fever, extreme tachycardia, and delirium with thyrotoxicosis','The key is severe systemic decompensation in a hormone-excess state. This is more than an uncomplicated outpatient symptom list.',[['Cold intolerance with mild constipation alone','That favors low hormone rather than storm.'],['Only an asymptomatic low ferritin','That is an iron-store finding.'],['A normal T4 with no clinical symptoms automatically proves storm','Clinical assessment is necessary.']]),
 q('Which factor can precipitate thyroid storm?','Infection or another major physiologic stressor','An already vulnerable thyrotoxic patient may decompensate with stress such as infection, trauma, or surgery.',[['Only low dietary iron, with no other factors ever','Storm has multiple possible precipitating factors.'],['All cases require a thyroid biopsy','A biopsy is not required to trigger or diagnose every case.'],['It only occurs in newborns','It is not restricted to newborns.']]),
 q('Does an isolated very high free T4 establish thyroid storm?','No, storm is assessed from the clinical decompensation','Severe fever, cardiovascular effects, CNS changes, and other organ involvement distinguish the clinical emergency.',[['Yes, every elevated T4 is storm','Uncomplicated hyperthyroidism can also elevate T4.'],['Yes, symptoms never matter','Clinical features are central.'],['No thyroid emergency ever affects the heart','Cardiac complications can be severe.']]),
 q('A thyrotoxic patient develops fever, agitation, and a very rapid irregular pulse during infection. What needs urgent consideration?','Thyroid storm','The combination of a trigger and severe systemic findings raises concern for decompensated thyrotoxicosis. Emergency assessment should not wait for a particular lab cutoff.',[['Only uncomplicated hypothyroidism','The described direction is hormone excess with severe fast/hot findings.'],['A harmless symptom that never needs reassessment','The pattern can be life-threatening.'],['Pernicious anemia as the sole mechanism','That does not explain the acute thyroid-excess crisis.']],'Apply'),
 q('Why does storm treatment use medicines with different targets?','Symptoms, new hormone synthesis, hormone release, and systemic support require different actions','A single symptomatic measure does not necessarily address continuing hormone activity or organ failure. The clinical team uses a coordinated regimen.',[['All drugs perform exactly the same action','Different treatments target symptoms, synthesis, release, or systemic support, so their actions are complementary.'],['Beta-blockade alone always removes every source of hormone','It mainly addresses adrenergic effects.'],['Supportive care has no role','Airway, circulation, temperature, and metabolic support can be essential.']],'Apply'),
 q('Hypothermia, slowed breathing, and reduced consciousness occur with severe hypothyroidism. Which emergency pattern fits?','Myxedema emergency','These are decompensated low-hormone findings. They contrast with the hot, fast pattern of thyroid storm.',[['Thyroid storm from deficient hormone','Storm is linked to thyrotoxicosis.'],['Ordinary mild symptoms that cannot become serious','Severe hypothyroidism can become an emergency.'],['Goiter alone proves the diagnosis','A gland’s size does not establish the emergency.']],'Apply')
 ])
 ]
});
