import {SHOCK_CASES,ANEMIA_CASES,SEIZURE_PATTERNS,HIV_STEPS,HIV_TARGETS,THYROID_TARGETS,cardiacOutput,estimatedMAP,oxygenCapacityRatio,thyroidPattern} from './visual-models.mjs';
import {LESSON_NOTES} from './visual-notes.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const choose=(key,value,label,active)=>`<button id="viz-${key}-${value}" type="button" class="viz-choice ${active?'selected':''}" data-action="viz" data-key="${key}" data-value="${value}" aria-pressed="${!!active}">${esc(label)}</button>`;
const chips=(key,data,current)=>`<div class="viz-choices">${Object.entries(data).map(([id,x])=>choose(key,id,x.label,id===current)).join('')}</div>`;
export const visualValueLabel=(key,value)=>key==='thyroidOutput'?['Low','Balanced','High'][Number(value)]:value;
const range=(key,label,min,max,value,unit='',step=1)=>`<div class="viz-slider"><label for="viz-${key}">${esc(label)}<output id="viz-value-${key}" for="viz-${key}">${esc(visualValueLabel(key,value))}${unit?' '+esc(unit):''}</output></label><input id="viz-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-viz-key="${key}" data-unit="${unit}"><div class="viz-range-ends"><span>${esc(visualValueLabel(key,min))}${unit?' '+esc(unit):''}</span><span>${esc(visualValueLabel(key,max))}${unit?' '+esc(unit):''}</span></div></div>`;
const select=(key,label,data,value)=>`<label class="viz-select" for="viz-${key}">${esc(label)}<select id="viz-${key}" data-viz-key="${key}">${Object.entries(data).map(([id,x])=>`<option value="${id}" ${id===value?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label>`;
const note=(title,text)=>`<div class="viz-insight"><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;
const metrics=rows=>`<dl class="viz-metrics">${rows.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;
const svgStart=(label,height=240)=>`<div class="viz-diagram-scroll" tabindex="0" role="region" aria-label="${esc(label)}. Scroll horizontally on a narrow screen."><svg class="viz-svg" viewBox="0 0 720 ${height}" role="img" aria-label="${esc(label)}">`;
const box=(x,y,w,h,label,sub='',active=false)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${active?'#ddf5ec':'#f3f7fb'}" stroke="${active?'#007f78':'#cbdce5'}" stroke-width="${active?2:1}"/><text x="${x+w/2}" y="${y+29}" text-anchor="middle" class="viz-diagram-title">${esc(label)}</text>${sub?`<text x="${x+w/2}" y="${y+51}" text-anchor="middle" class="viz-diagram-small">${esc(sub)}</text>`:''}`;
const link=(x1,y1,x2,y2)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="#718a99" stroke-width="2" fill="none"/><path d="M${x2} ${y2}L${x2-8} ${y2-5}L${x2-8} ${y2+5}z" fill="#718a99"/>`;

export function visualControlsHTML(t,s){
 let body='';
 if(t.id==='shock')body=chips('mode',{main:{label:'Blood flow'},pressure:{label:'MAP estimate'},compare:{label:'Shock mechanisms'}},s.mode)+(s.mode==='main'?range('hr','Heart rate (HR)',40,160,s.hr,'beats/min')+range('sv','Stroke volume (SV)',20,120,s.sv,'mL/beat'):s.mode==='pressure'?range('sbp','Systolic pressure',70,200,s.sbp,'mmHg')+range('dbp','Diastolic pressure',40,120,s.dbp,'mmHg'):select('shockCase','Compare the mechanism',SHOCK_CASES,s.shockCase));
 if(t.id==='anemia')body=select('anemiaCase','Choose an anemia pattern',ANEMIA_CASES,s.anemiaCase)+range('hb','Hemoglobin in the model',3,18,s.hb,'g/dL',.5);
 if(t.id==='thyroid')body=`<div class="viz-choices">${[['balanced','Balanced feedback'],['low','Primary low hormone'],['high','Primary excess hormone'],['central','Central deficiency']].map(([id,label])=>choose('thyroidPreset',id,label,(id==='central'?s.central&&s.thyroidOutput===0:!s.central&&s.thyroidOutput===({balanced:1,low:0,high:2})[id]))).join('')}</div>`+range('thyroidOutput','Thyroid hormone output',0,2,s.thyroidOutput)+`<label class="viz-checkbox"><input id="viz-central" type="checkbox" data-viz-key="central" ${s.central?'checked':''}>Central deficiency example</label>`+select('target','Explore a treatment target',THYROID_TARGETS,s.target);
 if(t.id==='seizures')body=select('seizureType','Choose a seizure pattern',SEIZURE_PATTERNS,s.seizureType)+`<div class="viz-choices">${SEIZURE_PATTERNS[s.seizureType].phases.map(([label],i)=>choose('phase',i,label,i===s.phase)).join('')}</div>`;
 if(t.id==='hiv')body=select('hivTarget','Explore a drug target',HIV_TARGETS,s.hivTarget)+`<ol class="viz-stage-picker">${HIV_STEPS.map((x,i)=>`<li>${choose('hivStep',i,`${i+1}. ${x.title}`,i===s.hivStep)}</li>`).join('')}</ol><label class="viz-checkbox"><input id="viz-art" type="checkbox" data-viz-key="art" ${s.art?'checked':''}>Compare the direction of effective ART</label>`;
 return `<div class="viz-control-heading"><span class="eyebrow">Try a change</span><h3>${esc({shock:'Flow, pressure, and mechanisms',anemia:'Find what changes in the blood',thyroid:'Follow the hormone messages',seizures:'See the event in phases',hiv:'Follow the replication steps'}[t.id])}</h3></div>${body}${choose('reset','true','Reset this visual',false)}`;
}

function shockOutput(s){
 if(s.mode==='compare'){
  const c=SHOCK_CASES[s.shockCase];
  return svgStart(`${c.label}: compare volume, pump, route, and vessel tone`,225)+box(20,70,140,75,'Volume',c.focus===0?'Reduced':'Circulating',c.focus===0)+link(165,108,194,108)+box(200,70,140,75,'Pump',c.focus===1?'Failing':'Heart output',c.focus===1)+link(345,108,374,108)+box(380,70,140,75,'Route',c.focus===2?'Obstructed':'Central flow',c.focus===2)+link(525,108,554,108)+box(560,70,140,75,'Vessel tone',c.focus===3?'Disrupted':'Distribution',c.focus===3)+`<text x="360" y="194" text-anchor="middle" class="viz-diagram-small">All four support tissue perfusion</text></svg></div>`+metrics([['Volume',c.volume],['Pump',c.pump],['Route',c.route],['Vessel tone',c.tone]])+note(c.label,c.explanation)+`<p class="viz-caption">${esc(c.clue)}</p>`;
 }
 if(s.mode==='pressure'){
  const map=estimatedMAP(s.sbp,s.dbp);
  return `<div class="viz-number-board"><span class="viz-big-number">${map.toFixed(1)}<small>mmHg</small></span><span>Estimated mean arterial pressure</span></div><div class="viz-equation">(${s.sbp} + 2 × ${s.dbp}) ÷ 3 = <strong>${map.toFixed(1)}</strong></div>`+svgStart('The resting MAP estimate weights diastolic pressure twice',150)+box(45,40,165,70,'Systolic',`${s.sbp} mmHg`)+box(275,40,165,70,'Diastolic × 2',`${2*s.dbp} mmHg`)+box(505,40,165,70,'Divide by 3',`${map.toFixed(1)} mmHg`,true)+'</svg></div>'+note('Why diastole gets extra weight','At a typical resting rhythm, the heart spends more of the cycle in diastole. This is an estimate; pressure and cardiac output are separate measurements.')+`<p class="viz-caption">The sliders change the arithmetic inputs. They do not predict pressure from a shock type.</p>`;
 }
 const co=cardiacOutput(s.hr,s.sv),perMinute=s.hr*s.sv;
 const dots=Array.from({length:8},(_,i)=>`<circle cx="${90+i*77}" cy="127" r="${Math.min(11,4+s.sv/16)}" fill="#159785" opacity=".75"/>`).join('');
 return `<div class="viz-number-board"><span class="viz-big-number">${co.toFixed(2)}<small>L/min</small></span><span>Cardiac output (CO)</span></div><div class="viz-equation">${s.hr} beats/min × ${s.sv} mL/beat = <strong>${perMinute.toLocaleString()} mL/min</strong></div>`+svgStart(`${s.hr} beats per minute, ${s.sv} milliliters per beat, cardiac output ${co.toFixed(2)} liters per minute`,240)+box(35,25,170,70,'Rate',`${s.hr} beats/min`)+box(275,25,170,70,'Per beat',`${s.sv} mL/beat`)+box(515,25,170,70,'Per minute',`${co.toFixed(2)} L/min`,true)+`<rect x="35" y="109" width="650" height="36" rx="18" fill="#e5f5ef" stroke="#b3d8cd"/>${dots}<rect x="35" y="179" width="650" height="18" rx="9" fill="#e5edf3"/><rect x="35" y="179" width="${650*Math.min(1,co/19.2)}" height="18" rx="9" fill="#007f78"/><text x="360" y="226" text-anchor="middle" class="viz-diagram-small">Output bar uses the slider maximum as its scale</text></svg></div>`+note('One beat versus one minute','Stroke volume is the amount moved by one beat. Cardiac output multiplies that amount by the number of beats each minute. A faster rate can offset some loss of stroke volume in this arithmetic model.')+`<p class="viz-caption">Try halving stroke volume while holding rate still, then double the rate. In real physiology, rate can also affect filling; the controls isolate the formula.</p>`;
}

function anemiaOutput(s){
 const c=ANEMIA_CASES[s.anemiaCase],ratio=oxygenCapacityRatio(s.hb);
 const cells=Array.from({length:c.count},(_,i)=>`<circle cx="${72+61*(i%5)}" cy="${65+47*Math.floor(i/5)}" r="${c.radius}" fill="${c.pale?'#f3bdc8':'#b3445e'}" stroke="#a5344f" stroke-width="1.5"/>`).join('');
 return `<div class="viz-number-board"><span class="viz-big-number">${Math.round(ratio*100)}<small>%</small></span><span>Relative hemoglobin oxygen-carrying capacity</span></div><div class="viz-capacity"><div class="viz-capacity-track"><span style="width:${ratio/1.2*100}%"></span><i style="left:83.333%" aria-hidden="true"></i></div><p class="viz-caption">${s.hb} ÷ 15 = ${ratio.toFixed(2)}. Reference Hb: 15 g/dL, chosen for the comparison; oxygen saturation is held constant.</p></div>`+svgStart(`${c.label}. Cell symbols illustrate ${c.size}; ${c.count} symbols show a qualitative comparison, not a blood count.`,310)+`<text x="200" y="27" text-anchor="middle" class="viz-diagram-title">Cell-size / quantity symbols</text>${cells}`+box(405,48,270,75,'Production',c.production,c.focus===0)+box(405,139,270,75,'Survival',c.survival,c.focus===1)+`<text x="200" y="263" text-anchor="middle" class="viz-diagram-small">${esc(c.size)}</text><text x="360" y="296" text-anchor="middle" class="viz-diagram-small">Symbols are not a blood smear or measured cell count</text></svg></div>`+note(c.label,c.explanation)+`<ul class="viz-clues">${c.clues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="viz-caption">The case selector compares mechanisms. The independent Hb slider isolates carrying capacity; it does not diagnose an anemia type.</p>`;
}

function thyroidOutput(s){
 const p=thyroidPattern(s.thyroidOutput,s.central),target=THYROID_TARGETS[s.target];
 const tshShort=s.central?'Low / normal*':s.thyroidOutput===0?'TSH high':s.thyroidOutput===2?'TSH low':'TSH balanced';
 return svgStart(`Hypothalamus sends TRH; pituitary sends TSH; thyroid produces T3 and T4. Current hormone output ${p.hormone}; TSH ${p.tsh}.`,290)+box(15,65,155,75,'Hypothalamus','TRH',s.central)+link(176,104,189,104)+box(195,65,155,75,'Pituitary',tshShort,s.central)+link(356,104,369,104)+box(375,65,155,75,'Thyroid',`T3 / T4: ${p.hormone}`,target.node===2)+link(536,104,549,104)+box(555,65,155,75,'Body effects',s.thyroidOutput===0?'Slower':s.thyroidOutput===2?'Faster':'Balanced',target.node===3)+`<path d="M452 146V207H92V146M272 207V146" stroke="#8464a8" stroke-width="2.5" fill="none"/><path d="M92 146L87 154L97 154zM272 146L267 154L277 154z" fill="#8464a8"/><text x="273" y="239" text-anchor="middle" class="viz-diagram-small">Negative feedback regulates upstream stimulation</text></svg></div>`+metrics([['Thyroid hormone',p.hormone],['TSH',p.tsh]])+note('Read the feedback',p.feedback)+`<ul class="viz-clues">${p.symptoms.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`+note(target.label,target.text)+`<p class="viz-caption">${s.central?'* Central deficiency can have low or inappropriately normal TSH despite low free T4. ':'The opposite TSH–hormone directions describe overt primary gland disease. '}Goiter describes gland size and can occur with high, low, or normal hormone function.</p>`;
}

function seizureOutput(s){
 const p=SEIZURE_PATTERNS[s.seizureType],phase=p.phases[s.phase],during=s.phase>0&&!(s.seizureType==='tonicClonic'&&s.phase===3)&&!(s.seizureType!=='tonicClonic'&&s.phase===2),focal=s.seizureType.startsWith('focal');
 const networks=[0,1].map(side=>{
  const x=25+side*365,active=during&&(!focal||side===0),nodes=Array.from({length:8},(_,i)=>({x:x+46+(i%4)*68,y:81+Math.floor(i/4)*53}));
  return `<rect x="${x}" y="35" width="330" height="140" rx="16" fill="${active?'#e4f6ef':'#f2f6fa'}" stroke="${active?'#007f78':'#cadbe5'}"/><text x="${x+165}" y="60" text-anchor="middle" class="viz-diagram-title">${side?'Right':'Left'} hemisphere</text>`+nodes.slice(0,7).map((n,i)=>`<line x1="${n.x}" y1="${n.y}" x2="${nodes[i+1].x}" y2="${nodes[i+1].y}" stroke="${active?'#60af9c':'#ccd9e2'}" stroke-width="2"/>`).join('')+nodes.map(n=>`<circle cx="${n.x}" cy="${n.y}" r="9" fill="${active?'#168a78':'#a4b9c6'}"/>`).join('');
 }).join('');
 const points=Array.from({length:81},(_,i)=>{
  let y=294;
  if(during){
   if(s.seizureType==='tonicClonic')y=s.phase===1?251:294-32*Math.sin(i*.55);
   if(s.seizureType==='atonic')y=i<23?273:323;
   if(s.seizureType==='myoclonic')y=i>=32&&i<=38?294-57*(1-Math.abs(i-35)/3):294;
  }
  return `${45+i*7.8},${y}`;
 }).join(' ');
 return `<div class="viz-phase-heading"><span class="pill">Phase ${s.phase+1} / ${p.phases.length}</span><h3>${esc(phase[0])}</h3></div>`+svgStart(`${p.label}, phase ${phase[0]}. Network activity is a schematic example.`,355)+networks+`<text x="360" y="208" text-anchor="middle" class="viz-diagram-small">${focal?'Focal onset: one-hemisphere network':'Distributed-network example; onset can depend on the seizure type'}</text><text x="360" y="239" text-anchor="middle" class="viz-diagram-title">Muscle-pattern schematic</text><path d="M42 248V329H681" fill="none" stroke="#cbdbe5" stroke-width="1.5"/><polyline points="${points}" fill="none" stroke="#007f78" stroke-width="3" stroke-linejoin="round"/><text x="360" y="352" text-anchor="middle" class="viz-diagram-small">Pattern illustration only — this is not an EEG recording</text></svg></div>`+metrics([['Onset / network',p.onset],['Awareness during event',p.awareness],['Motor pattern',p.motor]])+note(phase[0],phase[1])+`<p class="viz-caption">The network and line are schematic. Focal manifestations can vary; a motor appearance alone does not establish onset. Time the event, protect from injury, and assess breathing and recovery.</p>`;
}

function hivOutput(s){
 const step=HIV_STEPS[s.hivStep],target=HIV_TARGETS[s.hivTarget],blocked=s.hivTarget!=='none'&&step.target===s.hivTarget;
 const markers=HIV_STEPS.map((x,i)=>`<circle cx="${67+i*97}" cy="213" r="${i===s.hivStep?16:11}" fill="${x.target===s.hivTarget&&s.hivTarget!=='none'?'#ffe5c0':i===s.hivStep?'#008176':'#e4edf3'}" stroke="${i===s.hivStep?'#00675e':'#b6cad6'}"/><text x="${67+i*97}" y="218" text-anchor="middle" class="viz-diagram-small" style="fill:${i===s.hivStep?'#fff':'#173649'}">${i+1}</text>`).join('');
 return `<div class="viz-phase-heading"><span class="pill">Step ${s.hivStep+1} / 7</span><h3>${esc(step.title)}</h3></div>`+svgStart(`${step.title}: ${step.input} becomes ${step.output}. ${blocked?'Selected drug target acts at this step.':''}`,255)+box(25,55,190,85,'Input',step.input)+link(221,96,254,96)+box(260,55,200,85,'Process',step.enzyme,true)+link(466,96,499,96)+box(505,55,190,85,'Output',step.output)+`${blocked?'<path d="M274 43L445 151M445 43L274 151" stroke="#b05e20" stroke-width="3"/><text x="360" y="176" text-anchor="middle" class="viz-diagram-small">Drug target disrupts this step</text>':''}${markers}<text x="360" y="249" text-anchor="middle" class="viz-diagram-small">Select a stage to follow the viral process</text></svg></div>`+note(step.label,step.text)+note(target.label,`${target.text}${s.hivTarget!=='none'?' The amber marker identifies the target stage. Drug-class exploration is not a complete regimen.':''}`)+`<div class="viz-trend-heading"><h4>${s.art?'Effective ART: direction of change':'Without effective suppression'}</h4></div>`+svgStart(s.art?'Direction only: viral load decreases; CD4 count can recover.':'Direction only: untreated replication can increase while CD4 helper cells are lost.',180)+`<text x="40" y="27" class="viz-diagram-title">Viral load</text><text x="405" y="27" class="viz-diagram-title">CD4 helper cells</text><path d="M40 40V139H316M405 40V139H681" fill="none" stroke="#cbdce5" stroke-width="1.5"/><path d="${s.art?'M58 52C115 65 180 115 292 123':'M58 123C125 116 192 66 292 52'}" fill="none" stroke="#b3445e" stroke-width="4"/><path d="${s.art?'M423 123C490 116 557 68 657 52':'M423 52C490 66 557 115 657 123'}" fill="none" stroke="#007f78" stroke-width="4"/><text x="178" y="168" text-anchor="middle" class="viz-diagram-small">${s.art?'Falls with suppression':'Can rise with replication'}</text><text x="543" y="168" text-anchor="middle" class="viz-diagram-small">${s.art?'Can improve':'Can decline'}</text></svg></div><p class="viz-caption">The trend lines show direction only, with no patient timeline or magnitude. ART suppresses replication; persistent integrated templates can remain. Late assembly, budding, and maturation overlap.</p>`;
}

export function visualOutputHTML(t,l,s){
 let widget=t.id==='shock'?shockOutput(s):'';
 // Other topic renderers are defined below so the output remains independent
 // of the controls. Range dragging can update this region without losing focus.
 if(t.id==='anemia')widget=anemiaOutput(s);
 if(t.id==='thyroid')widget=thyroidOutput(s);
 if(t.id==='seizures')widget=seizureOutput(s);
 if(t.id==='hiv')widget=hivOutput(s);
 return `<div class="viz-output-inner">${widget}</div>`;
}

export function lessonMapHTML(l,s){
 const notes=LESSON_NOTES[l.id],step=Math.min(s.lessonStep,l.flow.length-1);
 return `<section class="viz-lesson-map"><div class="eyebrow">Connect this lesson</div><h3>${esc(l.title)}</h3><p class="muted">Select each part to see the connection.</p><ol class="viz-causal-picker">${l.flow.map((label,i)=>`<li>${choose('lessonStep',i,label,i===step)}</li>`).join('')}</ol><div class="viz-step-note" role="status"><span class="pill">${step+1} / ${l.flow.length}</span><h4>${esc(l.flow[step])}</h4><p>${esc(notes[step])}</p></div><p class="viz-memory"><strong>Memory cue:</strong> ${esc(l.memory)}</p></section>`;
}

export function visualLabHTML(t,l,s){
 const glossary={shock:'HR = heart rate. SV = stroke volume. CO = cardiac output. MAP = mean arterial pressure.',anemia:'RBC = red blood cell. Hb = hemoglobin. MCV = mean corpuscular volume, the average red-cell size.',thyroid:'TRH = thyrotropin-releasing hormone. TSH = thyroid-stimulating hormone. T3 = triiodothyronine. T4 = thyroxine.',seizures:'EEG = electroencephalogram, a recording of brain electrical activity. Postictal means after the seizure.',hiv:'RNA = ribonucleic acid. DNA = deoxyribonucleic acid. CD4 cells are helper immune cells. ART = antiretroviral therapy.'}[t.id];
 return `<div class="mode-header"><div><div class="eyebrow">Step 02 · Explore the concept</div><h2>Visual Lab</h2><p>Change a value or select a pattern, then connect what you see to the lesson.</p></div><span class="pill">${esc(t.title)}</span></div><div class="viz-lab"><section class="viz-controls" aria-label="Interactive visualization controls">${visualControlsHTML(t,s)}</section><section id="viz-output" class="viz-output" aria-label="Visualization results">${visualOutputHTML(t,l,s)}</section></div><p class="viz-glossary">${esc(glossary)}</p><div id="viz-lesson-map">${lessonMapHTML(l,s)}</div><p class="source-note">Teaching diagrams show the relationships being studied. Symbols and comparison bars are schematic; only the displayed formulas calculate numerical results. <a href="${t.source}#page=${parseInt(l.pages,10)}" target="_blank" rel="noopener">Open this lesson’s slides</a>.</p>`;
}
